# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/chihjung/Documents/maya/2023/scripts/ui/fxToolsEdgeMotionTrail.ui',
# licensing of 'C:/Users/chihjung/Documents/maya/2023/scripts/ui/fxToolsEdgeMotionTrail.ui' applies.
#
# Created: Thu Sep  8 12:14:43 2022
#      by: pyside2-uic  running on PySide2 5.12.5
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_main_widget(object):
    def setupUi(self, main_widget):
        main_widget.setObjectName("main_widget")
        main_widget.resize(300, 157)
        self.verticalLayout = QtWidgets.QVBoxLayout(main_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(main_widget)
        self.label.setMinimumSize(QtCore.QSize(100, 20))
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startFrame_LE = QtWidgets.QLineEdit(main_widget)
        self.startFrame_LE.setMaximumSize(QtCore.QSize(100, 16777215))
        self.startFrame_LE.setObjectName("startFrame_LE")
        self.horizontalLayout.addWidget(self.startFrame_LE)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(main_widget)
        self.label_2.setMinimumSize(QtCore.QSize(100, 20))
        self.label_2.setMaximumSize(QtCore.QSize(100, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.endFrame_LE = QtWidgets.QLineEdit(main_widget)
        self.endFrame_LE.setMaximumSize(QtCore.QSize(100, 16777215))
        self.endFrame_LE.setObjectName("endFrame_LE")
        self.horizontalLayout_2.addWidget(self.endFrame_LE)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_3 = QtWidgets.QLabel(main_widget)
        self.label_3.setMinimumSize(QtCore.QSize(100, 20))
        self.label_3.setMaximumSize(QtCore.QSize(100, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.step_LE = QtWidgets.QLineEdit(main_widget)
        self.step_LE.setMaximumSize(QtCore.QSize(100, 16777215))
        self.step_LE.setObjectName("step_LE")
        self.horizontalLayout_3.addWidget(self.step_LE)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_4 = QtWidgets.QLabel(main_widget)
        self.label_4.setMinimumSize(QtCore.QSize(100, 20))
        self.label_4.setMaximumSize(QtCore.QSize(100, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.newPolyName_LE = QtWidgets.QLineEdit(main_widget)
        self.newPolyName_LE.setMaximumSize(QtCore.QSize(100, 16777215))
        self.newPolyName_LE.setObjectName("newPolyName_LE")
        self.horizontalLayout_5.addWidget(self.newPolyName_LE)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.trailGo_PB = QtWidgets.QPushButton(main_widget)
        self.trailGo_PB.setObjectName("trailGo_PB")
        self.horizontalLayout_4.addWidget(self.trailGo_PB)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(main_widget)
        QtCore.QMetaObject.connectSlotsByName(main_widget)

    def retranslateUi(self, main_widget):
        main_widget.setWindowTitle(QtWidgets.QApplication.translate("main_widget", "Form", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("main_widget", "Start Frame", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("main_widget", "End Frame", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("main_widget", "Step", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("main_widget", "New Poly Name", None, -1))
        self.trailGo_PB.setText(QtWidgets.QApplication.translate("main_widget", "Go", None, -1))

