# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/chihjung/Documents/maya/2017/scripts/ui/pixiTools_export_json.ui'
#
# Created: Mon Mar 12 09:50:21 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_main_widget(object):
    def setupUi(self, main_widget):
        main_widget.setObjectName("main_widget")
        main_widget.resize(800, 593)
        self.verticalLayout = QtWidgets.QVBoxLayout(main_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.flag_commend_layout = QtWidgets.QFormLayout()
        self.flag_commend_layout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.flag_commend_layout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.flag_commend_layout.setContentsMargins(2, 2, 2, 2)
        self.flag_commend_layout.setHorizontalSpacing(8)
        self.flag_commend_layout.setVerticalSpacing(4)
        self.flag_commend_layout.setObjectName("flag_commend_layout")
        self.create_plane_label = QtWidgets.QLabel(main_widget)
        self.create_plane_label.setMinimumSize(QtCore.QSize(140, 0))
        self.create_plane_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.create_plane_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.create_plane_label.setObjectName("create_plane_label")
        self.flag_commend_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.create_plane_label)
        self.createPlane_layout = QtWidgets.QHBoxLayout()
        self.createPlane_layout.setSpacing(4)
        self.createPlane_layout.setObjectName("createPlane_layout")
        self.createPlaneW_label = QtWidgets.QLabel(main_widget)
        self.createPlaneW_label.setMinimumSize(QtCore.QSize(30, 0))
        self.createPlaneW_label.setAlignment(QtCore.Qt.AlignCenter)
        self.createPlaneW_label.setObjectName("createPlaneW_label")
        self.createPlane_layout.addWidget(self.createPlaneW_label)
        self.createPlaneW_LE = QtWidgets.QLineEdit(main_widget)
        self.createPlaneW_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.createPlaneW_LE.setObjectName("createPlaneW_LE")
        self.createPlane_layout.addWidget(self.createPlaneW_LE)
        self.createPlaneH_label = QtWidgets.QLabel(main_widget)
        self.createPlaneH_label.setMinimumSize(QtCore.QSize(30, 0))
        self.createPlaneH_label.setAlignment(QtCore.Qt.AlignCenter)
        self.createPlaneH_label.setObjectName("createPlaneH_label")
        self.createPlane_layout.addWidget(self.createPlaneH_label)
        self.createPlaneH_LE = QtWidgets.QLineEdit(main_widget)
        self.createPlaneH_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.createPlaneH_LE.setObjectName("createPlaneH_LE")
        self.createPlane_layout.addWidget(self.createPlaneH_LE)
        self.createPlane_PB = QtWidgets.QPushButton(main_widget)
        self.createPlane_PB.setObjectName("createPlane_PB")
        self.createPlane_layout.addWidget(self.createPlane_PB)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.createPlane_layout.addItem(spacerItem)
        self.flag_commend_layout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.createPlane_layout)
        self.particle_name_label = QtWidgets.QLabel(main_widget)
        self.particle_name_label.setMinimumSize(QtCore.QSize(140, 0))
        self.particle_name_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.particle_name_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.particle_name_label.setObjectName("particle_name_label")
        self.flag_commend_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.particle_name_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.particleName_LE = QtWidgets.QLineEdit(main_widget)
        self.particleName_LE.setMaximumSize(QtCore.QSize(120, 16777215))
        self.particleName_LE.setObjectName("particleName_LE")
        self.horizontalLayout_2.addWidget(self.particleName_LE)
        self.bakeToObject_PB = QtWidgets.QPushButton(main_widget)
        self.bakeToObject_PB.setMaximumSize(QtCore.QSize(170, 16777215))
        self.bakeToObject_PB.setObjectName("bakeToObject_PB")
        self.horizontalLayout_2.addWidget(self.bakeToObject_PB)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.flag_commend_layout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.objGrp_label = QtWidgets.QLabel(main_widget)
        self.objGrp_label.setMinimumSize(QtCore.QSize(140, 0))
        self.objGrp_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.objGrp_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.objGrp_label.setObjectName("objGrp_label")
        self.flag_commend_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.objGrp_label)
        self.objGrp_LE = QtWidgets.QLineEdit(main_widget)
        self.objGrp_LE.setMaximumSize(QtCore.QSize(160, 16777215))
        self.objGrp_LE.setObjectName("objGrp_LE")
        self.flag_commend_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.objGrp_LE)
        self.instanceGrp_label = QtWidgets.QLabel(main_widget)
        self.instanceGrp_label.setMinimumSize(QtCore.QSize(140, 0))
        self.instanceGrp_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.instanceGrp_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.instanceGrp_label.setObjectName("instanceGrp_label")
        self.flag_commend_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.instanceGrp_label)
        self.instanceGrp_LE = QtWidgets.QLineEdit(main_widget)
        self.instanceGrp_LE.setEnabled(True)
        self.instanceGrp_LE.setMaximumSize(QtCore.QSize(160, 16777215))
        self.instanceGrp_LE.setObjectName("instanceGrp_LE")
        self.flag_commend_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.instanceGrp_LE)
        self.sourceCam_label = QtWidgets.QLabel(main_widget)
        self.sourceCam_label.setMinimumSize(QtCore.QSize(140, 0))
        self.sourceCam_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.sourceCam_label.setSizeIncrement(QtCore.QSize(0, 0))
        self.sourceCam_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sourceCam_label.setObjectName("sourceCam_label")
        self.flag_commend_layout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.sourceCam_label)
        self.sourceCam_LE = QtWidgets.QLineEdit(main_widget)
        self.sourceCam_LE.setMaximumSize(QtCore.QSize(160, 16777215))
        self.sourceCam_LE.setObjectName("sourceCam_LE")
        self.flag_commend_layout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sourceCam_LE)
        self.frameRange_label = QtWidgets.QLabel(main_widget)
        self.frameRange_label.setMinimumSize(QtCore.QSize(140, 0))
        self.frameRange_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.frameRange_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.frameRange_label.setObjectName("frameRange_label")
        self.flag_commend_layout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.frameRange_label)
        self.frameRange_layout = QtWidgets.QHBoxLayout()
        self.frameRange_layout.setSpacing(4)
        self.frameRange_layout.setObjectName("frameRange_layout")
        self.frameRangeStart_label = QtWidgets.QLabel(main_widget)
        self.frameRangeStart_label.setMinimumSize(QtCore.QSize(30, 0))
        self.frameRangeStart_label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frameRangeStart_label.setAlignment(QtCore.Qt.AlignCenter)
        self.frameRangeStart_label.setObjectName("frameRangeStart_label")
        self.frameRange_layout.addWidget(self.frameRangeStart_label)
        self.frameRangeStart_LE = QtWidgets.QLineEdit(main_widget)
        self.frameRangeStart_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frameRangeStart_LE.setMaxLength(4)
        self.frameRangeStart_LE.setObjectName("frameRangeStart_LE")
        self.frameRange_layout.addWidget(self.frameRangeStart_LE)
        self.frameRangeEnd_label = QtWidgets.QLabel(main_widget)
        self.frameRangeEnd_label.setMinimumSize(QtCore.QSize(30, 0))
        self.frameRangeEnd_label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frameRangeEnd_label.setAlignment(QtCore.Qt.AlignCenter)
        self.frameRangeEnd_label.setObjectName("frameRangeEnd_label")
        self.frameRange_layout.addWidget(self.frameRangeEnd_label)
        self.frameRangeEnd_LE = QtWidgets.QLineEdit(main_widget)
        self.frameRangeEnd_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frameRangeEnd_LE.setObjectName("frameRangeEnd_LE")
        self.frameRange_layout.addWidget(self.frameRangeEnd_LE)
        self.frameRangeStep_label = QtWidgets.QLabel(main_widget)
        self.frameRangeStep_label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frameRangeStep_label.setAlignment(QtCore.Qt.AlignCenter)
        self.frameRangeStep_label.setObjectName("frameRangeStep_label")
        self.frameRange_layout.addWidget(self.frameRangeStep_label)
        self.frameRangeStep_LE = QtWidgets.QLineEdit(main_widget)
        self.frameRangeStep_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frameRangeStep_LE.setObjectName("frameRangeStep_LE")
        self.frameRange_layout.addWidget(self.frameRangeStep_LE)
        self.time_label = QtWidgets.QLabel(main_widget)
        self.time_label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.frameRange_layout.addWidget(self.time_label)
        self.frameRangeTime_CB = QtWidgets.QComboBox(main_widget)
        self.frameRangeTime_CB.setObjectName("frameRangeTime_CB")
        self.frameRangeTime_CB.addItem("")
        self.frameRangeTime_CB.addItem("")
        self.frameRangeTime_CB.addItem("")
        self.frameRange_layout.addWidget(self.frameRangeTime_CB)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.frameRange_layout.addItem(spacerItem2)
        self.flag_commend_layout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.frameRange_layout)
        self.sourceSize_label = QtWidgets.QLabel(main_widget)
        self.sourceSize_label.setMinimumSize(QtCore.QSize(140, 0))
        self.sourceSize_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.sourceSize_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sourceSize_label.setObjectName("sourceSize_label")
        self.flag_commend_layout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.sourceSize_label)
        self.sourceSize_layout = QtWidgets.QHBoxLayout()
        self.sourceSize_layout.setSpacing(4)
        self.sourceSize_layout.setObjectName("sourceSize_layout")
        self.sourceSizeW_label = QtWidgets.QLabel(main_widget)
        self.sourceSizeW_label.setMinimumSize(QtCore.QSize(30, 0))
        self.sourceSizeW_label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.sourceSizeW_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sourceSizeW_label.setObjectName("sourceSizeW_label")
        self.sourceSize_layout.addWidget(self.sourceSizeW_label)
        self.sourceSizeW_LE = QtWidgets.QLineEdit(main_widget)
        self.sourceSizeW_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.sourceSizeW_LE.setObjectName("sourceSizeW_LE")
        self.sourceSize_layout.addWidget(self.sourceSizeW_LE)
        self.sourceSizeH_label = QtWidgets.QLabel(main_widget)
        self.sourceSizeH_label.setMinimumSize(QtCore.QSize(30, 0))
        self.sourceSizeH_label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.sourceSizeH_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sourceSizeH_label.setObjectName("sourceSizeH_label")
        self.sourceSize_layout.addWidget(self.sourceSizeH_label)
        self.sourceSizeH_LE = QtWidgets.QLineEdit(main_widget)
        self.sourceSizeH_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.sourceSizeH_LE.setObjectName("sourceSizeH_LE")
        self.sourceSize_layout.addWidget(self.sourceSizeH_LE)
        self.sourceCam_setUp_PB = QtWidgets.QPushButton(main_widget)
        self.sourceCam_setUp_PB.setObjectName("sourceCam_setUp_PB")
        self.sourceSize_layout.addWidget(self.sourceCam_setUp_PB)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.sourceSize_layout.addItem(spacerItem3)
        self.flag_commend_layout.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.sourceSize_layout)
        self.canvasSize_label = QtWidgets.QLabel(main_widget)
        self.canvasSize_label.setMinimumSize(QtCore.QSize(140, 0))
        self.canvasSize_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.canvasSize_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.canvasSize_label.setObjectName("canvasSize_label")
        self.flag_commend_layout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.canvasSize_label)
        self.canvasSize_layout = QtWidgets.QHBoxLayout()
        self.canvasSize_layout.setSpacing(4)
        self.canvasSize_layout.setObjectName("canvasSize_layout")
        self.canvasSizeW_label = QtWidgets.QLabel(main_widget)
        self.canvasSizeW_label.setMinimumSize(QtCore.QSize(30, 0))
        self.canvasSizeW_label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.canvasSizeW_label.setAlignment(QtCore.Qt.AlignCenter)
        self.canvasSizeW_label.setObjectName("canvasSizeW_label")
        self.canvasSize_layout.addWidget(self.canvasSizeW_label)
        self.canvasSizeW_LE = QtWidgets.QLineEdit(main_widget)
        self.canvasSizeW_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.canvasSizeW_LE.setObjectName("canvasSizeW_LE")
        self.canvasSize_layout.addWidget(self.canvasSizeW_LE)
        self.canvasSizeH_label = QtWidgets.QLabel(main_widget)
        self.canvasSizeH_label.setMinimumSize(QtCore.QSize(30, 0))
        self.canvasSizeH_label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.canvasSizeH_label.setAlignment(QtCore.Qt.AlignCenter)
        self.canvasSizeH_label.setObjectName("canvasSizeH_label")
        self.canvasSize_layout.addWidget(self.canvasSizeH_label)
        self.canvasSizeH_LE = QtWidgets.QLineEdit(main_widget)
        self.canvasSizeH_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.canvasSizeH_LE.setObjectName("canvasSizeH_LE")
        self.canvasSize_layout.addWidget(self.canvasSizeH_LE)
        self.canvasCam_setUp_PB = QtWidgets.QPushButton(main_widget)
        self.canvasCam_setUp_PB.setObjectName("canvasCam_setUp_PB")
        self.canvasSize_layout.addWidget(self.canvasCam_setUp_PB)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.canvasSize_layout.addItem(spacerItem4)
        self.flag_commend_layout.setLayout(8, QtWidgets.QFormLayout.FieldRole, self.canvasSize_layout)
        self.exportPath_label = QtWidgets.QLabel(main_widget)
        self.exportPath_label.setMinimumSize(QtCore.QSize(140, 0))
        self.exportPath_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.exportPath_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.exportPath_label.setObjectName("exportPath_label")
        self.flag_commend_layout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.exportPath_label)
        self.outDir_layout = QtWidgets.QHBoxLayout()
        self.outDir_layout.setSpacing(2)
        self.outDir_layout.setObjectName("outDir_layout")
        self.outDir_LE = QtWidgets.QLineEdit(main_widget)
        self.outDir_LE.setObjectName("outDir_LE")
        self.outDir_layout.addWidget(self.outDir_LE)
        self.outDirBro_PB = QtWidgets.QPushButton(main_widget)
        self.outDirBro_PB.setMaximumSize(QtCore.QSize(20, 16777215))
        self.outDirBro_PB.setObjectName("outDirBro_PB")
        self.outDir_layout.addWidget(self.outDirBro_PB)
        self.outDirOpen_PB = QtWidgets.QPushButton(main_widget)
        self.outDirOpen_PB.setObjectName("outDirOpen_PB")
        self.outDir_layout.addWidget(self.outDirOpen_PB)
        self.flag_commend_layout.setLayout(9, QtWidgets.QFormLayout.FieldRole, self.outDir_layout)
        self.jsonName_label = QtWidgets.QLabel(main_widget)
        self.jsonName_label.setMinimumSize(QtCore.QSize(140, 0))
        self.jsonName_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.jsonName_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jsonName_label.setObjectName("jsonName_label")
        self.flag_commend_layout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.jsonName_label)
        self.jsonName_layout = QtWidgets.QHBoxLayout()
        self.jsonName_layout.setObjectName("jsonName_layout")
        self.json_LE = QtWidgets.QLineEdit(main_widget)
        self.json_LE.setMaximumSize(QtCore.QSize(120, 16777215))
        self.json_LE.setObjectName("json_LE")
        self.jsonName_layout.addWidget(self.json_LE)
        self.json_label = QtWidgets.QLabel(main_widget)
        self.json_label.setObjectName("json_label")
        self.jsonName_layout.addWidget(self.json_label)
        self.flag_commend_layout.setLayout(10, QtWidgets.QFormLayout.FieldRole, self.jsonName_layout)
        self.exportOption_label = QtWidgets.QLabel(main_widget)
        self.exportOption_label.setMinimumSize(QtCore.QSize(140, 0))
        self.exportOption_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.exportOption_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.exportOption_label.setObjectName("exportOption_label")
        self.flag_commend_layout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.exportOption_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scale_CB = QtWidgets.QCheckBox(main_widget)
        self.scale_CB.setChecked(True)
        self.scale_CB.setObjectName("scale_CB")
        self.horizontalLayout.addWidget(self.scale_CB)
        self.rotation_CB = QtWidgets.QCheckBox(main_widget)
        self.rotation_CB.setChecked(True)
        self.rotation_CB.setObjectName("rotation_CB")
        self.horizontalLayout.addWidget(self.rotation_CB)
        self.rgbpp_CB = QtWidgets.QCheckBox(main_widget)
        self.rgbpp_CB.setObjectName("rgbpp_CB")
        self.horizontalLayout.addWidget(self.rgbpp_CB)
        self.zdepth_CB = QtWidgets.QCheckBox(main_widget)
        self.zdepth_CB.setObjectName("zdepth_CB")
        self.horizontalLayout.addWidget(self.zdepth_CB)
        self.cropBroders_CB = QtWidgets.QCheckBox(main_widget)
        self.cropBroders_CB.setObjectName("cropBroders_CB")
        self.horizontalLayout.addWidget(self.cropBroders_CB)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.flag_commend_layout.setLayout(12, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.textureMode_label = QtWidgets.QLabel(main_widget)
        self.textureMode_label.setMinimumSize(QtCore.QSize(140, 0))
        self.textureMode_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.textureMode_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textureMode_label.setObjectName("textureMode_label")
        self.flag_commend_layout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.textureMode_label)
        self.textureMode_layout = QtWidgets.QHBoxLayout()
        self.textureMode_layout.setObjectName("textureMode_layout")
        self.textureMode_01_RB = QtWidgets.QRadioButton(main_widget)
        self.textureMode_01_RB.setObjectName("textureMode_01_RB")
        self.textureMode_layout.addWidget(self.textureMode_01_RB)
        self.textureMode_02_RB = QtWidgets.QRadioButton(main_widget)
        self.textureMode_02_RB.setObjectName("textureMode_02_RB")
        self.textureMode_layout.addWidget(self.textureMode_02_RB)
        self.textureMode_03_RB = QtWidgets.QRadioButton(main_widget)
        self.textureMode_03_RB.setObjectName("textureMode_03_RB")
        self.textureMode_layout.addWidget(self.textureMode_03_RB)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.textureMode_layout.addItem(spacerItem6)
        self.flag_commend_layout.setLayout(11, QtWidgets.QFormLayout.FieldRole, self.textureMode_layout)
        self.canvasCam_label = QtWidgets.QLabel(main_widget)
        self.canvasCam_label.setMinimumSize(QtCore.QSize(140, 0))
        self.canvasCam_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.canvasCam_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.canvasCam_label.setObjectName("canvasCam_label")
        self.flag_commend_layout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.canvasCam_label)
        self.canvasCam_LE = QtWidgets.QLineEdit(main_widget)
        self.canvasCam_LE.setMaximumSize(QtCore.QSize(160, 16777215))
        self.canvasCam_LE.setObjectName("canvasCam_LE")
        self.flag_commend_layout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.canvasCam_LE)
        self.verticalLayout.addLayout(self.flag_commend_layout)
        self.shaderSetToDefault_PB = QtWidgets.QPushButton(main_widget)
        self.shaderSetToDefault_PB.setObjectName("shaderSetToDefault_PB")
        self.verticalLayout.addWidget(self.shaderSetToDefault_PB)
        self.exportJson_PB = QtWidgets.QPushButton(main_widget)
        self.exportJson_PB.setObjectName("exportJson_PB")
        self.verticalLayout.addWidget(self.exportJson_PB)
        self.info_label = QtWidgets.QLabel(main_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.info_label.setFont(font)
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setObjectName("info_label")
        self.verticalLayout.addWidget(self.info_label)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)

        self.retranslateUi(main_widget)
        QtCore.QMetaObject.connectSlotsByName(main_widget)

    def retranslateUi(self, main_widget):
        main_widget.setWindowTitle(QtWidgets.QApplication.translate("main_widget", "Form", None, -1))
        self.create_plane_label.setText(QtWidgets.QApplication.translate("main_widget", "Set Create Plane", None, -1))
        self.createPlaneW_label.setText(QtWidgets.QApplication.translate("main_widget", "width", None, -1))
        self.createPlaneW_LE.setText(QtWidgets.QApplication.translate("main_widget", "20", None, -1))
        self.createPlaneH_label.setText(QtWidgets.QApplication.translate("main_widget", "height", None, -1))
        self.createPlaneH_LE.setText(QtWidgets.QApplication.translate("main_widget", "40", None, -1))
        self.createPlane_PB.setText(QtWidgets.QApplication.translate("main_widget", "Create", None, -1))
        self.particle_name_label.setText(QtWidgets.QApplication.translate("main_widget", "particle name", None, -1))
        self.bakeToObject_PB.setText(QtWidgets.QApplication.translate("main_widget", "Bake To Object", None, -1))
        self.objGrp_label.setText(QtWidgets.QApplication.translate("main_widget", "Objects Group", None, -1))
        self.instanceGrp_label.setText(QtWidgets.QApplication.translate("main_widget", "Instance Group", None, -1))
        self.sourceCam_label.setText(QtWidgets.QApplication.translate("main_widget", "Source Camera", None, -1))
        self.frameRange_label.setText(QtWidgets.QApplication.translate("main_widget", "Frame Range", None, -1))
        self.frameRangeStart_label.setText(QtWidgets.QApplication.translate("main_widget", "start", None, -1))
        self.frameRangeStart_LE.setText(QtWidgets.QApplication.translate("main_widget", "1", None, -1))
        self.frameRangeEnd_label.setText(QtWidgets.QApplication.translate("main_widget", "end", None, -1))
        self.frameRangeEnd_LE.setText(QtWidgets.QApplication.translate("main_widget", "1", None, -1))
        self.frameRangeStep_label.setText(QtWidgets.QApplication.translate("main_widget", "step", None, -1))
        self.frameRangeStep_LE.setText(QtWidgets.QApplication.translate("main_widget", "1", None, -1))
        self.time_label.setText(QtWidgets.QApplication.translate("main_widget", "time", None, -1))
        self.frameRangeTime_CB.setItemText(0, QtWidgets.QApplication.translate("main_widget", "24 fps", None, -1))
        self.frameRangeTime_CB.setItemText(1, QtWidgets.QApplication.translate("main_widget", "30 fps", None, -1))
        self.frameRangeTime_CB.setItemText(2, QtWidgets.QApplication.translate("main_widget", "60 fps", None, -1))
        self.sourceSize_label.setText(QtWidgets.QApplication.translate("main_widget", "Source Size", None, -1))
        self.sourceSizeW_label.setText(QtWidgets.QApplication.translate("main_widget", "width", None, -1))
        self.sourceSizeW_LE.setText(QtWidgets.QApplication.translate("main_widget", "1080", None, -1))
        self.sourceSizeH_label.setText(QtWidgets.QApplication.translate("main_widget", "height", None, -1))
        self.sourceSizeH_LE.setText(QtWidgets.QApplication.translate("main_widget", "1080", None, -1))
        self.sourceCam_setUp_PB.setText(QtWidgets.QApplication.translate("main_widget", "Set Up", None, -1))
        self.canvasSize_label.setText(QtWidgets.QApplication.translate("main_widget", "Canvas Size", None, -1))
        self.canvasSizeW_label.setText(QtWidgets.QApplication.translate("main_widget", "width", None, -1))
        self.canvasSizeW_LE.setText(QtWidgets.QApplication.translate("main_widget", "1920", None, -1))
        self.canvasSizeH_label.setText(QtWidgets.QApplication.translate("main_widget", "height", None, -1))
        self.canvasSizeH_LE.setText(QtWidgets.QApplication.translate("main_widget", "1080", None, -1))
        self.canvasCam_setUp_PB.setText(QtWidgets.QApplication.translate("main_widget", "Set Up", None, -1))
        self.exportPath_label.setText(QtWidgets.QApplication.translate("main_widget", "Export Path", None, -1))
        self.outDirBro_PB.setText(QtWidgets.QApplication.translate("main_widget", "...", None, -1))
        self.outDirOpen_PB.setText(QtWidgets.QApplication.translate("main_widget", "open", None, -1))
        self.jsonName_label.setText(QtWidgets.QApplication.translate("main_widget", "Json Name", None, -1))
        self.json_label.setText(QtWidgets.QApplication.translate("main_widget", ".json", None, -1))
        self.exportOption_label.setText(QtWidgets.QApplication.translate("main_widget", "Export Option", None, -1))
        self.scale_CB.setText(QtWidgets.QApplication.translate("main_widget", "Scale", None, -1))
        self.rotation_CB.setText(QtWidgets.QApplication.translate("main_widget", "Rotation", None, -1))
        self.rgbpp_CB.setText(QtWidgets.QApplication.translate("main_widget", "RgbPP", None, -1))
        self.zdepth_CB.setText(QtWidgets.QApplication.translate("main_widget", "ZDepth", None, -1))
        self.cropBroders_CB.setText(QtWidgets.QApplication.translate("main_widget", "Border Falloff", None, -1))
        self.textureMode_label.setText(QtWidgets.QApplication.translate("main_widget", "Texture Mode", None, -1))
        self.textureMode_01_RB.setText(QtWidgets.QApplication.translate("main_widget", "Sequence", None, -1))
        self.textureMode_02_RB.setText(QtWidgets.QApplication.translate("main_widget", "Single-Frame Multi-Images", None, -1))
        self.textureMode_03_RB.setText(QtWidgets.QApplication.translate("main_widget", "Single-Frame Single-Image", None, -1))
        self.canvasCam_label.setText(QtWidgets.QApplication.translate("main_widget", "Canvas Camera", None, -1))
        self.shaderSetToDefault_PB.setText(QtWidgets.QApplication.translate("main_widget", "Shader Set To Default Layer", None, -1))
        self.exportJson_PB.setText(QtWidgets.QApplication.translate("main_widget", "Export Json", None, -1))
        self.info_label.setText(QtWidgets.QApplication.translate("main_widget", "Doing...", None, -1))

