# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/chihjung/Documents/maya/2018/scripts/ui/pixiTools_particleEdit.ui'
#
# Created: Mon Jul 15 11:31:35 2019
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_main_widget(object):
    def setupUi(self, main_widget):
        main_widget.setObjectName("main_widget")
        main_widget.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(main_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.flag_commend_layout = QtWidgets.QFormLayout()
        self.flag_commend_layout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.flag_commend_layout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.flag_commend_layout.setContentsMargins(2, 2, 2, 2)
        self.flag_commend_layout.setHorizontalSpacing(8)
        self.flag_commend_layout.setVerticalSpacing(4)
        self.flag_commend_layout.setObjectName("flag_commend_layout")
        self.textureFile_label = QtWidgets.QLabel(main_widget)
        self.textureFile_label.setMinimumSize(QtCore.QSize(140, 0))
        self.textureFile_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.textureFile_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textureFile_label.setObjectName("textureFile_label")
        self.flag_commend_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.textureFile_label)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.textureFile_LE = QtWidgets.QLineEdit(main_widget)
        self.textureFile_LE.setObjectName("textureFile_LE")
        self.horizontalLayout_11.addWidget(self.textureFile_LE)
        self.textureFileBro_PB = QtWidgets.QPushButton(main_widget)
        self.textureFileBro_PB.setMaximumSize(QtCore.QSize(20, 16777215))
        self.textureFileBro_PB.setObjectName("textureFileBro_PB")
        self.horizontalLayout_11.addWidget(self.textureFileBro_PB)
        self.textureFileOpen_PB = QtWidgets.QPushButton(main_widget)
        self.textureFileOpen_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.textureFileOpen_PB.setObjectName("textureFileOpen_PB")
        self.horizontalLayout_11.addWidget(self.textureFileOpen_PB)
        self.flag_commend_layout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.textureSize_label = QtWidgets.QLabel(main_widget)
        self.textureSize_label.setMinimumSize(QtCore.QSize(140, 0))
        self.textureSize_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.textureSize_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textureSize_label.setObjectName("textureSize_label")
        self.flag_commend_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.textureSize_label)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(2)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.texWidth_label = QtWidgets.QLabel(main_widget)
        self.texWidth_label.setMinimumSize(QtCore.QSize(40, 0))
        self.texWidth_label.setMaximumSize(QtCore.QSize(40, 16777215))
        self.texWidth_label.setObjectName("texWidth_label")
        self.horizontalLayout_13.addWidget(self.texWidth_label)
        self.texWidth_LE = QtWidgets.QLineEdit(main_widget)
        self.texWidth_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.texWidth_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.texWidth_LE.setObjectName("texWidth_LE")
        self.horizontalLayout_13.addWidget(self.texWidth_LE)
        self.texHeight_label = QtWidgets.QLabel(main_widget)
        self.texHeight_label.setMinimumSize(QtCore.QSize(40, 0))
        self.texHeight_label.setMaximumSize(QtCore.QSize(40, 16777215))
        self.texHeight_label.setObjectName("texHeight_label")
        self.horizontalLayout_13.addWidget(self.texHeight_label)
        self.texHeight_LE = QtWidgets.QLineEdit(main_widget)
        self.texHeight_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.texHeight_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.texHeight_LE.setObjectName("texHeight_LE")
        self.horizontalLayout_13.addWidget(self.texHeight_LE)
        self.createPlane_PB = QtWidgets.QPushButton(main_widget)
        self.createPlane_PB.setObjectName("createPlane_PB")
        self.horizontalLayout_13.addWidget(self.createPlane_PB)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.flag_commend_layout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_13)
        self.instanceGrpName_label = QtWidgets.QLabel(main_widget)
        self.instanceGrpName_label.setMinimumSize(QtCore.QSize(140, 0))
        self.instanceGrpName_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.instanceGrpName_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.instanceGrpName_label.setObjectName("instanceGrpName_label")
        self.flag_commend_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.instanceGrpName_label)
        self.instanceGrpName_layout = QtWidgets.QHBoxLayout()
        self.instanceGrpName_layout.setSpacing(2)
        self.instanceGrpName_layout.setObjectName("instanceGrpName_layout")
        self.instanceGrpName_LE = QtWidgets.QLineEdit(main_widget)
        self.instanceGrpName_LE.setMaximumSize(QtCore.QSize(160, 16777215))
        self.instanceGrpName_LE.setObjectName("instanceGrpName_LE")
        self.instanceGrpName_layout.addWidget(self.instanceGrpName_LE)
        self.instanceGrpName_PB = QtWidgets.QPushButton(main_widget)
        self.instanceGrpName_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.instanceGrpName_PB.setObjectName("instanceGrpName_PB")
        self.instanceGrpName_layout.addWidget(self.instanceGrpName_PB)
        self.deleteKey_PB = QtWidgets.QPushButton(main_widget)
        self.deleteKey_PB.setObjectName("deleteKey_PB")
        self.instanceGrpName_layout.addWidget(self.deleteKey_PB)
        self.convertJointMode_PB = QtWidgets.QPushButton(main_widget)
        self.convertJointMode_PB.setObjectName("convertJointMode_PB")
        self.instanceGrpName_layout.addWidget(self.convertJointMode_PB)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.instanceGrpName_layout.addItem(spacerItem1)
        self.flag_commend_layout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.instanceGrpName_layout)
        self.verticalLayout.addLayout(self.flag_commend_layout)
        self.line = QtWidgets.QFrame(main_widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(2, 2, 2, 2)
        self.formLayout.setHorizontalSpacing(8)
        self.formLayout.setVerticalSpacing(4)
        self.formLayout.setObjectName("formLayout")
        self.randomKey_label = QtWidgets.QLabel(main_widget)
        self.randomKey_label.setMinimumSize(QtCore.QSize(140, 0))
        self.randomKey_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.randomKey_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.randomKey_label.setObjectName("randomKey_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.randomKey_label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.randomKeyMin_LE = QtWidgets.QLineEdit(main_widget)
        self.randomKeyMin_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.randomKeyMin_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.randomKeyMin_LE.setObjectName("randomKeyMin_LE")
        self.horizontalLayout_3.addWidget(self.randomKeyMin_LE)
        self.randomKeyMax_LE = QtWidgets.QLineEdit(main_widget)
        self.randomKeyMax_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.randomKeyMax_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.randomKeyMax_LE.setObjectName("randomKeyMax_LE")
        self.horizontalLayout_3.addWidget(self.randomKeyMax_LE)
        self.randomKeySet_PB = QtWidgets.QPushButton(main_widget)
        self.randomKeySet_PB.setObjectName("randomKeySet_PB")
        self.horizontalLayout_3.addWidget(self.randomKeySet_PB)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.startFrame_label = QtWidgets.QLabel(main_widget)
        self.startFrame_label.setMinimumSize(QtCore.QSize(140, 0))
        self.startFrame_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.startFrame_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.startFrame_label.setObjectName("startFrame_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.startFrame_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startFrame_LE = QtWidgets.QLineEdit(main_widget)
        self.startFrame_LE.setMinimumSize(QtCore.QSize(100, 0))
        self.startFrame_LE.setMaximumSize(QtCore.QSize(100, 16777215))
        self.startFrame_LE.setObjectName("startFrame_LE")
        self.horizontalLayout.addWidget(self.startFrame_LE)
        self.startFrameSet_PB = QtWidgets.QPushButton(main_widget)
        self.startFrameSet_PB.setObjectName("startFrameSet_PB")
        self.horizontalLayout.addWidget(self.startFrameSet_PB)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.loopKey_label = QtWidgets.QLabel(main_widget)
        self.loopKey_label.setMinimumSize(QtCore.QSize(140, 0))
        self.loopKey_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.loopKey_label.setObjectName("loopKey_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.loopKey_label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.startFrameLoop_label = QtWidgets.QLabel(main_widget)
        self.startFrameLoop_label.setMinimumSize(QtCore.QSize(60, 0))
        self.startFrameLoop_label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.startFrameLoop_label.setObjectName("startFrameLoop_label")
        self.horizontalLayout_4.addWidget(self.startFrameLoop_label)
        self.startFrameLoop_LE = QtWidgets.QLineEdit(main_widget)
        self.startFrameLoop_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.startFrameLoop_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.startFrameLoop_LE.setObjectName("startFrameLoop_LE")
        self.horizontalLayout_4.addWidget(self.startFrameLoop_LE)
        self.endFrameLoop_label = QtWidgets.QLabel(main_widget)
        self.endFrameLoop_label.setMinimumSize(QtCore.QSize(60, 0))
        self.endFrameLoop_label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.endFrameLoop_label.setObjectName("endFrameLoop_label")
        self.horizontalLayout_4.addWidget(self.endFrameLoop_label)
        self.endFrameLoop_LE = QtWidgets.QLineEdit(main_widget)
        self.endFrameLoop_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.endFrameLoop_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.endFrameLoop_LE.setObjectName("endFrameLoop_LE")
        self.horizontalLayout_4.addWidget(self.endFrameLoop_LE)
        self.frequency_label = QtWidgets.QLabel(main_widget)
        self.frequency_label.setMinimumSize(QtCore.QSize(60, 0))
        self.frequency_label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.frequency_label.setObjectName("frequency_label")
        self.horizontalLayout_4.addWidget(self.frequency_label)
        self.frequency_LE = QtWidgets.QLineEdit(main_widget)
        self.frequency_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.frequency_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frequency_LE.setObjectName("frequency_LE")
        self.horizontalLayout_4.addWidget(self.frequency_LE)
        self.goLoop_PB = QtWidgets.QPushButton(main_widget)
        self.goLoop_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.goLoop_PB.setObjectName("goLoop_PB")
        self.horizontalLayout_4.addWidget(self.goLoop_PB)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.adjustmentTime_label = QtWidgets.QLabel(main_widget)
        self.adjustmentTime_label.setMinimumSize(QtCore.QSize(140, 0))
        self.adjustmentTime_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.adjustmentTime_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.adjustmentTime_label.setObjectName("adjustmentTime_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.adjustmentTime_label)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.centerFrame_label = QtWidgets.QLabel(main_widget)
        self.centerFrame_label.setObjectName("centerFrame_label")
        self.horizontalLayout_7.addWidget(self.centerFrame_label)
        self.centerFrame_LE = QtWidgets.QLineEdit(main_widget)
        self.centerFrame_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.centerFrame_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.centerFrame_LE.setObjectName("centerFrame_LE")
        self.horizontalLayout_7.addWidget(self.centerFrame_LE)
        self.speed_label = QtWidgets.QLabel(main_widget)
        self.speed_label.setObjectName("speed_label")
        self.horizontalLayout_7.addWidget(self.speed_label)
        self.speed_SB = QtWidgets.QDoubleSpinBox(main_widget)
        self.speed_SB.setMaximum(10.0)
        self.speed_SB.setSingleStep(0.05)
        self.speed_SB.setProperty("value", 1.0)
        self.speed_SB.setObjectName("speed_SB")
        self.horizontalLayout_7.addWidget(self.speed_SB)
        self.speedConvertTime_PB = QtWidgets.QPushButton(main_widget)
        self.speedConvertTime_PB.setObjectName("speedConvertTime_PB")
        self.horizontalLayout_7.addWidget(self.speedConvertTime_PB)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.verticalLayout.addLayout(self.formLayout)
        self.line_2 = QtWidgets.QFrame(main_widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(2, 2, 2, 2)
        self.formLayout_2.setHorizontalSpacing(8)
        self.formLayout_2.setVerticalSpacing(4)
        self.formLayout_2.setObjectName("formLayout_2")
        self.randomAttributeSelect_label = QtWidgets.QLabel(main_widget)
        self.randomAttributeSelect_label.setMinimumSize(QtCore.QSize(140, 0))
        self.randomAttributeSelect_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.randomAttributeSelect_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.randomAttributeSelect_label.setObjectName("randomAttributeSelect_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.randomAttributeSelect_label)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.translateX_RB = QtWidgets.QRadioButton(main_widget)
        self.translateX_RB.setObjectName("translateX_RB")
        self.horizontalLayout_6.addWidget(self.translateX_RB)
        self.translateY_RB = QtWidgets.QRadioButton(main_widget)
        self.translateY_RB.setObjectName("translateY_RB")
        self.horizontalLayout_6.addWidget(self.translateY_RB)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.scale_RB = QtWidgets.QRadioButton(main_widget)
        self.scale_RB.setObjectName("scale_RB")
        self.horizontalLayout_8.addWidget(self.scale_RB)
        self.scaleX_RB = QtWidgets.QRadioButton(main_widget)
        self.scaleX_RB.setObjectName("scaleX_RB")
        self.horizontalLayout_8.addWidget(self.scaleX_RB)
        self.scaleY_RB = QtWidgets.QRadioButton(main_widget)
        self.scaleY_RB.setObjectName("scaleY_RB")
        self.horizontalLayout_8.addWidget(self.scaleY_RB)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.rotateZ_RB = QtWidgets.QRadioButton(main_widget)
        self.rotateZ_RB.setObjectName("rotateZ_RB")
        self.horizontalLayout_9.addWidget(self.rotateZ_RB)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(4)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.alphaGain_RB = QtWidgets.QRadioButton(main_widget)
        self.alphaGain_RB.setEnabled(True)
        self.alphaGain_RB.setObjectName("alphaGain_RB")
        self.horizontalLayout_10.addWidget(self.alphaGain_RB)
        self.colorGain_RB = QtWidgets.QRadioButton(main_widget)
        self.colorGain_RB.setEnabled(True)
        self.colorGain_RB.setObjectName("colorGain_RB")
        self.horizontalLayout_10.addWidget(self.colorGain_RB)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_15.addLayout(self.verticalLayout_2)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_15)
        self.randomValueEdit_label = QtWidgets.QLabel(main_widget)
        self.randomValueEdit_label.setMinimumSize(QtCore.QSize(140, 0))
        self.randomValueEdit_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.randomValueEdit_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.randomValueEdit_label.setObjectName("randomValueEdit_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.randomValueEdit_label)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(2)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.minValue_label = QtWidgets.QLabel(main_widget)
        self.minValue_label.setObjectName("minValue_label")
        self.horizontalLayout_12.addWidget(self.minValue_label)
        self.minValue_LE = QtWidgets.QLineEdit(main_widget)
        self.minValue_LE.setMinimumSize(QtCore.QSize(80, 0))
        self.minValue_LE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.minValue_LE.setObjectName("minValue_LE")
        self.horizontalLayout_12.addWidget(self.minValue_LE)
        self.maxValue_label = QtWidgets.QLabel(main_widget)
        self.maxValue_label.setObjectName("maxValue_label")
        self.horizontalLayout_12.addWidget(self.maxValue_label)
        self.maxValue_LE = QtWidgets.QLineEdit(main_widget)
        self.maxValue_LE.setMinimumSize(QtCore.QSize(80, 0))
        self.maxValue_LE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.maxValue_LE.setObjectName("maxValue_LE")
        self.horizontalLayout_12.addWidget(self.maxValue_LE)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem10)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_12)
        self.randomSetKey_label = QtWidgets.QLabel(main_widget)
        self.randomSetKey_label.setMinimumSize(QtCore.QSize(140, 0))
        self.randomSetKey_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.randomSetKey_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.randomSetKey_label.setObjectName("randomSetKey_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.randomSetKey_label)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(2)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.offset_RB = QtWidgets.QRadioButton(main_widget)
        self.offset_RB.setObjectName("offset_RB")
        self.horizontalLayout_16.addWidget(self.offset_RB)
        self.replace_RB = QtWidgets.QRadioButton(main_widget)
        self.replace_RB.setCheckable(True)
        self.replace_RB.setChecked(True)
        self.replace_RB.setObjectName("replace_RB")
        self.horizontalLayout_16.addWidget(self.replace_RB)
        self.keyIndex_label = QtWidgets.QLabel(main_widget)
        self.keyIndex_label.setObjectName("keyIndex_label")
        self.horizontalLayout_16.addWidget(self.keyIndex_label)
        self.keyIndex_LE = QtWidgets.QLineEdit(main_widget)
        self.keyIndex_LE.setMinimumSize(QtCore.QSize(120, 0))
        self.keyIndex_LE.setMaximumSize(QtCore.QSize(120, 16777215))
        self.keyIndex_LE.setObjectName("keyIndex_LE")
        self.horizontalLayout_16.addWidget(self.keyIndex_LE)
        self.randomValueSetKey_PB = QtWidgets.QPushButton(main_widget)
        self.randomValueSetKey_PB.setObjectName("randomValueSetKey_PB")
        self.horizontalLayout_16.addWidget(self.randomValueSetKey_PB)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem11)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_16)
        self.adjustmentValue_label = QtWidgets.QLabel(main_widget)
        self.adjustmentValue_label.setMinimumSize(QtCore.QSize(140, 0))
        self.adjustmentValue_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.adjustmentValue_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.adjustmentValue_label.setObjectName("adjustmentValue_label")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.adjustmentValue_label)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.translate_label = QtWidgets.QLabel(main_widget)
        self.translate_label.setObjectName("translate_label")
        self.horizontalLayout_5.addWidget(self.translate_label)
        self.translate_SB = QtWidgets.QDoubleSpinBox(main_widget)
        self.translate_SB.setMaximum(10.0)
        self.translate_SB.setSingleStep(0.05)
        self.translate_SB.setProperty("value", 1.0)
        self.translate_SB.setObjectName("translate_SB")
        self.horizontalLayout_5.addWidget(self.translate_SB)
        self.translateConvertValue_PB = QtWidgets.QPushButton(main_widget)
        self.translateConvertValue_PB.setObjectName("translateConvertValue_PB")
        self.horizontalLayout_5.addWidget(self.translateConvertValue_PB)
        self.scale_label = QtWidgets.QLabel(main_widget)
        self.scale_label.setObjectName("scale_label")
        self.horizontalLayout_5.addWidget(self.scale_label)
        self.scale_SB = QtWidgets.QDoubleSpinBox(main_widget)
        self.scale_SB.setMaximum(10.0)
        self.scale_SB.setSingleStep(0.05)
        self.scale_SB.setProperty("value", 1.0)
        self.scale_SB.setObjectName("scale_SB")
        self.horizontalLayout_5.addWidget(self.scale_SB)
        self.scaleConvertValue_PB = QtWidgets.QPushButton(main_widget)
        self.scaleConvertValue_PB.setObjectName("scaleConvertValue_PB")
        self.horizontalLayout_5.addWidget(self.scaleConvertValue_PB)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.formLayout_2.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label = QtWidgets.QLabel(main_widget)
        self.label.setMinimumSize(QtCore.QSize(140, 0))
        self.label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.autoSetRotationKey_PB = QtWidgets.QPushButton(main_widget)
        self.autoSetRotationKey_PB.setObjectName("autoSetRotationKey_PB")
        self.horizontalLayout_2.addWidget(self.autoSetRotationKey_PB)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem13)
        self.formLayout_2.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.line_3 = QtWidgets.QFrame(main_widget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.flag_commend_layout_2 = QtWidgets.QFormLayout()
        self.flag_commend_layout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.flag_commend_layout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.flag_commend_layout_2.setContentsMargins(2, 2, 2, 2)
        self.flag_commend_layout_2.setHorizontalSpacing(8)
        self.flag_commend_layout_2.setVerticalSpacing(4)
        self.flag_commend_layout_2.setObjectName("flag_commend_layout_2")
        self.motionPathCurve_label = QtWidgets.QLabel(main_widget)
        self.motionPathCurve_label.setMinimumSize(QtCore.QSize(140, 0))
        self.motionPathCurve_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.motionPathCurve_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.motionPathCurve_label.setObjectName("motionPathCurve_label")
        self.flag_commend_layout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.motionPathCurve_label)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(2)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.motionPathCurve_LE = QtWidgets.QLineEdit(main_widget)
        self.motionPathCurve_LE.setObjectName("motionPathCurve_LE")
        self.horizontalLayout_14.addWidget(self.motionPathCurve_LE)
        self.motionPathAddCurve_PB = QtWidgets.QPushButton(main_widget)
        self.motionPathAddCurve_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.motionPathAddCurve_PB.setObjectName("motionPathAddCurve_PB")
        self.horizontalLayout_14.addWidget(self.motionPathAddCurve_PB)
        self.flag_commend_layout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_14)
        self.motionPathTextureSize_label = QtWidgets.QLabel(main_widget)
        self.motionPathTextureSize_label.setMinimumSize(QtCore.QSize(140, 0))
        self.motionPathTextureSize_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.motionPathTextureSize_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.motionPathTextureSize_label.setObjectName("motionPathTextureSize_label")
        self.flag_commend_layout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.motionPathTextureSize_label)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(2)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.joint_list_LE = QtWidgets.QLineEdit(main_widget)
        self.joint_list_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.joint_list_LE.setText("")
        self.joint_list_LE.setObjectName("joint_list_LE")
        self.horizontalLayout_17.addWidget(self.joint_list_LE)
        self.add_joint_PB = QtWidgets.QPushButton(main_widget)
        self.add_joint_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.add_joint_PB.setObjectName("add_joint_PB")
        self.horizontalLayout_17.addWidget(self.add_joint_PB)
        self.flag_commend_layout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_17)
        self.timeAndKey_label = QtWidgets.QLabel(main_widget)
        self.timeAndKey_label.setMinimumSize(QtCore.QSize(140, 0))
        self.timeAndKey_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.timeAndKey_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeAndKey_label.setObjectName("timeAndKey_label")
        self.flag_commend_layout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.timeAndKey_label)
        self.instanceGrpName_layout_2 = QtWidgets.QHBoxLayout()
        self.instanceGrpName_layout_2.setSpacing(2)
        self.instanceGrpName_layout_2.setObjectName("instanceGrpName_layout_2")
        self.motionPathStartFrame_label = QtWidgets.QLabel(main_widget)
        self.motionPathStartFrame_label.setMinimumSize(QtCore.QSize(60, 0))
        self.motionPathStartFrame_label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.motionPathStartFrame_label.setObjectName("motionPathStartFrame_label")
        self.instanceGrpName_layout_2.addWidget(self.motionPathStartFrame_label)
        self.motionPathStartFrame_LE = QtWidgets.QLineEdit(main_widget)
        self.motionPathStartFrame_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.motionPathStartFrame_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.motionPathStartFrame_LE.setObjectName("motionPathStartFrame_LE")
        self.instanceGrpName_layout_2.addWidget(self.motionPathStartFrame_LE)
        self.motionPathEndFrame_label = QtWidgets.QLabel(main_widget)
        self.motionPathEndFrame_label.setMinimumSize(QtCore.QSize(60, 0))
        self.motionPathEndFrame_label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.motionPathEndFrame_label.setObjectName("motionPathEndFrame_label")
        self.instanceGrpName_layout_2.addWidget(self.motionPathEndFrame_label)
        self.motionPathEndFrame_LE = QtWidgets.QLineEdit(main_widget)
        self.motionPathEndFrame_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.motionPathEndFrame_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.motionPathEndFrame_LE.setObjectName("motionPathEndFrame_LE")
        self.instanceGrpName_layout_2.addWidget(self.motionPathEndFrame_LE)
        self.motionPathKeys_label = QtWidgets.QLabel(main_widget)
        self.motionPathKeys_label.setMinimumSize(QtCore.QSize(40, 0))
        self.motionPathKeys_label.setMaximumSize(QtCore.QSize(40, 16777215))
        self.motionPathKeys_label.setObjectName("motionPathKeys_label")
        self.instanceGrpName_layout_2.addWidget(self.motionPathKeys_label)
        self.motionPathKeys_LE = QtWidgets.QLineEdit(main_widget)
        self.motionPathKeys_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.motionPathKeys_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.motionPathKeys_LE.setObjectName("motionPathKeys_LE")
        self.instanceGrpName_layout_2.addWidget(self.motionPathKeys_LE)
        self.motionPathPow_label = QtWidgets.QLabel(main_widget)
        self.motionPathPow_label.setMinimumSize(QtCore.QSize(40, 0))
        self.motionPathPow_label.setMaximumSize(QtCore.QSize(40, 16777215))
        self.motionPathPow_label.setObjectName("motionPathPow_label")
        self.instanceGrpName_layout_2.addWidget(self.motionPathPow_label)
        self.motionPathPow_LE = QtWidgets.QLineEdit(main_widget)
        self.motionPathPow_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.motionPathPow_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.motionPathPow_LE.setObjectName("motionPathPow_LE")
        self.instanceGrpName_layout_2.addWidget(self.motionPathPow_LE)
        self.curveAttach_PB = QtWidgets.QPushButton(main_widget)
        self.curveAttach_PB.setObjectName("curveAttach_PB")
        self.instanceGrpName_layout_2.addWidget(self.curveAttach_PB)
        self.resetPosition_PB = QtWidgets.QPushButton(main_widget)
        self.resetPosition_PB.setObjectName("resetPosition_PB")
        self.instanceGrpName_layout_2.addWidget(self.resetPosition_PB)
        self.flag_commend_layout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.instanceGrpName_layout_2)
        self.verticalLayout.addLayout(self.flag_commend_layout_2)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem14)

        self.retranslateUi(main_widget)
        QtCore.QMetaObject.connectSlotsByName(main_widget)

    def retranslateUi(self, main_widget):
        main_widget.setWindowTitle(QtWidgets.QApplication.translate("main_widget", "Form", None, -1))
        self.textureFile_label.setText(QtWidgets.QApplication.translate("main_widget", "Texture File", None, -1))
        self.textureFileBro_PB.setText(QtWidgets.QApplication.translate("main_widget", "...", None, -1))
        self.textureFileOpen_PB.setText(QtWidgets.QApplication.translate("main_widget", "Open", None, -1))
        self.textureSize_label.setText(QtWidgets.QApplication.translate("main_widget", "Texture Size", None, -1))
        self.texWidth_label.setText(QtWidgets.QApplication.translate("main_widget", "width", None, -1))
        self.texHeight_label.setText(QtWidgets.QApplication.translate("main_widget", "height", None, -1))
        self.createPlane_PB.setText(QtWidgets.QApplication.translate("main_widget", "Create Instance Plane", None, -1))
        self.instanceGrpName_label.setText(QtWidgets.QApplication.translate("main_widget", "Instance Grp Name", None, -1))
        self.instanceGrpName_PB.setText(QtWidgets.QApplication.translate("main_widget", "Pick", None, -1))
        self.deleteKey_PB.setText(QtWidgets.QApplication.translate("main_widget", "Optimize Key", None, -1))
        self.convertJointMode_PB.setText(QtWidgets.QApplication.translate("main_widget", "Convert Joint Mode", None, -1))
        self.randomKey_label.setText(QtWidgets.QApplication.translate("main_widget", "Random Key", None, -1))
        self.randomKeySet_PB.setText(QtWidgets.QApplication.translate("main_widget", "Set", None, -1))
        self.startFrame_label.setText(QtWidgets.QApplication.translate("main_widget", "Start Frame", None, -1))
        self.startFrame_LE.setText(QtWidgets.QApplication.translate("main_widget", "1", None, -1))
        self.startFrameSet_PB.setText(QtWidgets.QApplication.translate("main_widget", "Set", None, -1))
        self.loopKey_label.setText(QtWidgets.QApplication.translate("main_widget", "Loop Key", None, -1))
        self.startFrameLoop_label.setText(QtWidgets.QApplication.translate("main_widget", "start frame", None, -1))
        self.startFrameLoop_LE.setText(QtWidgets.QApplication.translate("main_widget", "1", None, -1))
        self.endFrameLoop_label.setText(QtWidgets.QApplication.translate("main_widget", "end frame", None, -1))
        self.frequency_label.setText(QtWidgets.QApplication.translate("main_widget", "frequency", None, -1))
        self.goLoop_PB.setText(QtWidgets.QApplication.translate("main_widget", "Go Loop", None, -1))
        self.adjustmentTime_label.setText(QtWidgets.QApplication.translate("main_widget", "Adjustment Time", None, -1))
        self.centerFrame_label.setText(QtWidgets.QApplication.translate("main_widget", "pivot frame", None, -1))
        self.centerFrame_LE.setText(QtWidgets.QApplication.translate("main_widget", "1", None, -1))
        self.speed_label.setText(QtWidgets.QApplication.translate("main_widget", "speed", None, -1))
        self.speedConvertTime_PB.setText(QtWidgets.QApplication.translate("main_widget", "Convert Time", None, -1))
        self.randomAttributeSelect_label.setText(QtWidgets.QApplication.translate("main_widget", "Random Attribute Select", None, -1))
        self.translateX_RB.setText(QtWidgets.QApplication.translate("main_widget", "translateX", None, -1))
        self.translateY_RB.setText(QtWidgets.QApplication.translate("main_widget", "translateY", None, -1))
        self.scale_RB.setText(QtWidgets.QApplication.translate("main_widget", "scale", None, -1))
        self.scaleX_RB.setText(QtWidgets.QApplication.translate("main_widget", "scaleX", None, -1))
        self.scaleY_RB.setText(QtWidgets.QApplication.translate("main_widget", "scaleY", None, -1))
        self.rotateZ_RB.setText(QtWidgets.QApplication.translate("main_widget", "rotateZ", None, -1))
        self.alphaGain_RB.setText(QtWidgets.QApplication.translate("main_widget", "alphaGain", None, -1))
        self.colorGain_RB.setText(QtWidgets.QApplication.translate("main_widget", "colorGain", None, -1))
        self.randomValueEdit_label.setText(QtWidgets.QApplication.translate("main_widget", "Random Value Edit", None, -1))
        self.minValue_label.setText(QtWidgets.QApplication.translate("main_widget", "min value", None, -1))
        self.maxValue_label.setText(QtWidgets.QApplication.translate("main_widget", "max value", None, -1))
        self.randomSetKey_label.setText(QtWidgets.QApplication.translate("main_widget", "Random Set Key", None, -1))
        self.offset_RB.setText(QtWidgets.QApplication.translate("main_widget", "offset", None, -1))
        self.replace_RB.setText(QtWidgets.QApplication.translate("main_widget", "replace", None, -1))
        self.keyIndex_label.setText(QtWidgets.QApplication.translate("main_widget", "key index [0,1,...]", None, -1))
        self.randomValueSetKey_PB.setText(QtWidgets.QApplication.translate("main_widget", "Set Key", None, -1))
        self.adjustmentValue_label.setText(QtWidgets.QApplication.translate("main_widget", "Adjustment Value", None, -1))
        self.translate_label.setText(QtWidgets.QApplication.translate("main_widget", "translate ", None, -1))
        self.translateConvertValue_PB.setText(QtWidgets.QApplication.translate("main_widget", "Convert Value", None, -1))
        self.scale_label.setText(QtWidgets.QApplication.translate("main_widget", "scale", None, -1))
        self.scaleConvertValue_PB.setText(QtWidgets.QApplication.translate("main_widget", "Convert Value", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("main_widget", "Other Function", None, -1))
        self.autoSetRotationKey_PB.setText(QtWidgets.QApplication.translate("main_widget", "Auto Set Rotation Keys", None, -1))
        self.motionPathCurve_label.setText(QtWidgets.QApplication.translate("main_widget", "Motion Path Curve", None, -1))
        self.motionPathAddCurve_PB.setText(QtWidgets.QApplication.translate("main_widget", "Add Curve", None, -1))
        self.motionPathTextureSize_label.setText(QtWidgets.QApplication.translate("main_widget", "Joint List", None, -1))
        self.add_joint_PB.setText(QtWidgets.QApplication.translate("main_widget", "Add Joint", None, -1))
        self.timeAndKey_label.setText(QtWidgets.QApplication.translate("main_widget", "time and key", None, -1))
        self.motionPathStartFrame_label.setText(QtWidgets.QApplication.translate("main_widget", "start frame", None, -1))
        self.motionPathStartFrame_LE.setText(QtWidgets.QApplication.translate("main_widget", "1", None, -1))
        self.motionPathEndFrame_label.setText(QtWidgets.QApplication.translate("main_widget", "end frame", None, -1))
        self.motionPathEndFrame_LE.setText(QtWidgets.QApplication.translate("main_widget", "30", None, -1))
        self.motionPathKeys_label.setText(QtWidgets.QApplication.translate("main_widget", "keys", None, -1))
        self.motionPathKeys_LE.setText(QtWidgets.QApplication.translate("main_widget", "10", None, -1))
        self.motionPathPow_label.setText(QtWidgets.QApplication.translate("main_widget", "pow", None, -1))
        self.motionPathPow_LE.setText(QtWidgets.QApplication.translate("main_widget", "1", None, -1))
        self.curveAttach_PB.setText(QtWidgets.QApplication.translate("main_widget", "Curve Attach", None, -1))
        self.resetPosition_PB.setText(QtWidgets.QApplication.translate("main_widget", "Reset Position", None, -1))

