# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/chihjung/Documents/maya/2023/scripts/ui/prmanR22_tools_vdbEdit.ui',
# licensing of 'C:/Users/chihjung/Documents/maya/2023/scripts/ui/prmanR22_tools_vdbEdit.ui' applies.
#
# Created: Tue Sep 13 17:01:57 2022
#      by: pyside2-uic  running on PySide2 5.12.5
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_main_widget(object):
    def setupUi(self, main_widget):
        main_widget.setObjectName("main_widget")
        main_widget.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(main_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.flag_commend_layout_3 = QtWidgets.QFormLayout()
        self.flag_commend_layout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.flag_commend_layout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.flag_commend_layout_3.setContentsMargins(2, 2, 2, 2)
        self.flag_commend_layout_3.setHorizontalSpacing(8)
        self.flag_commend_layout_3.setVerticalSpacing(4)
        self.flag_commend_layout_3.setObjectName("flag_commend_layout_3")
        self.targetVdb_label = QtWidgets.QLabel(main_widget)
        self.targetVdb_label.setMinimumSize(QtCore.QSize(140, 0))
        self.targetVdb_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.targetVdb_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.targetVdb_label.setObjectName("targetVdb_label")
        self.flag_commend_layout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.targetVdb_label)
        self.vdbFile_label = QtWidgets.QLabel(main_widget)
        self.vdbFile_label.setMinimumSize(QtCore.QSize(140, 0))
        self.vdbFile_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.vdbFile_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vdbFile_label.setObjectName("vdbFile_label")
        self.flag_commend_layout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.vdbFile_label)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(2)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.vdbFile_LE = QtWidgets.QLineEdit(main_widget)
        self.vdbFile_LE.setObjectName("vdbFile_LE")
        self.horizontalLayout_15.addWidget(self.vdbFile_LE)
        self.vdbBro_PB = QtWidgets.QPushButton(main_widget)
        self.vdbBro_PB.setMaximumSize(QtCore.QSize(20, 16777215))
        self.vdbBro_PB.setObjectName("vdbBro_PB")
        self.horizontalLayout_15.addWidget(self.vdbBro_PB)
        self.vdbOpen_PB = QtWidgets.QPushButton(main_widget)
        self.vdbOpen_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.vdbOpen_PB.setObjectName("vdbOpen_PB")
        self.horizontalLayout_15.addWidget(self.vdbOpen_PB)
        self.vdbFileSet_PB = QtWidgets.QPushButton(main_widget)
        self.vdbFileSet_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.vdbFileSet_PB.setObjectName("vdbFileSet_PB")
        self.horizontalLayout_15.addWidget(self.vdbFileSet_PB)
        self.flag_commend_layout_3.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_15)
        self.vdbSg_label = QtWidgets.QLabel(main_widget)
        self.vdbSg_label.setMinimumSize(QtCore.QSize(140, 0))
        self.vdbSg_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.vdbSg_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vdbSg_label.setObjectName("vdbSg_label")
        self.flag_commend_layout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.vdbSg_label)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.vdbSg_LE = QtWidgets.QLineEdit(main_widget)
        self.vdbSg_LE.setText("")
        self.vdbSg_LE.setObjectName("vdbSg_LE")
        self.horizontalLayout_6.addWidget(self.vdbSg_LE)
        self.getSg_PB = QtWidgets.QPushButton(main_widget)
        self.getSg_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.getSg_PB.setObjectName("getSg_PB")
        self.horizontalLayout_6.addWidget(self.getSg_PB)
        self.vdbSgSet_PB = QtWidgets.QPushButton(main_widget)
        self.vdbSgSet_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.vdbSgSet_PB.setObjectName("vdbSgSet_PB")
        self.horizontalLayout_6.addWidget(self.vdbSgSet_PB)
        self.flag_commend_layout_3.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(2)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.targetVdb_LE = QtWidgets.QLineEdit(main_widget)
        self.targetVdb_LE.setObjectName("targetVdb_LE")
        self.horizontalLayout_16.addWidget(self.targetVdb_LE)
        self.targetVdb_PB = QtWidgets.QPushButton(main_widget)
        self.targetVdb_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.targetVdb_PB.setObjectName("targetVdb_PB")
        self.horizontalLayout_16.addWidget(self.targetVdb_PB)
        self.flag_commend_layout_3.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_16)
        self.vdbView_label = QtWidgets.QLabel(main_widget)
        self.vdbView_label.setMinimumSize(QtCore.QSize(140, 0))
        self.vdbView_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.vdbView_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vdbView_label.setObjectName("vdbView_label")
        self.flag_commend_layout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.vdbView_label)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(2)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.renderAs_label = QtWidgets.QLabel(main_widget)
        self.renderAs_label.setObjectName("renderAs_label")
        self.horizontalLayout_17.addWidget(self.renderAs_label)
        self.renderAs_comboBox = QtWidgets.QComboBox(main_widget)
        self.renderAs_comboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.renderAs_comboBox.setObjectName("renderAs_comboBox")
        self.renderAs_comboBox.addItem("")
        self.renderAs_comboBox.addItem("")
        self.renderAs_comboBox.addItem("")
        self.horizontalLayout_17.addWidget(self.renderAs_comboBox)
        self.leafNode_CB = QtWidgets.QCheckBox(main_widget)
        self.leafNode_CB.setObjectName("leafNode_CB")
        self.horizontalLayout_17.addWidget(self.leafNode_CB)
        self.activeVoxels_CB = QtWidgets.QCheckBox(main_widget)
        self.activeVoxels_CB.setObjectName("activeVoxels_CB")
        self.horizontalLayout_17.addWidget(self.activeVoxels_CB)
        self.surface_CB = QtWidgets.QCheckBox(main_widget)
        self.surface_CB.setObjectName("surface_CB")
        self.horizontalLayout_17.addWidget(self.surface_CB)
        self.vdbSetView_PB = QtWidgets.QPushButton(main_widget)
        self.vdbSetView_PB.setObjectName("vdbSetView_PB")
        self.horizontalLayout_17.addWidget(self.vdbSetView_PB)
        self.setAllBox_PB = QtWidgets.QPushButton(main_widget)
        self.setAllBox_PB.setObjectName("setAllBox_PB")
        self.horizontalLayout_17.addWidget(self.setAllBox_PB)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem)
        self.flag_commend_layout_3.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_17)
        self.vdbView_label_2 = QtWidgets.QLabel(main_widget)
        self.vdbView_label_2.setMinimumSize(QtCore.QSize(140, 0))
        self.vdbView_label_2.setMaximumSize(QtCore.QSize(140, 16777215))
        self.vdbView_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vdbView_label_2.setObjectName("vdbView_label_2")
        self.flag_commend_layout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.vdbView_label_2)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(2)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.fixReadNode_PB = QtWidgets.QPushButton(main_widget)
        self.fixReadNode_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.fixReadNode_PB.setObjectName("fixReadNode_PB")
        self.horizontalLayout_18.addWidget(self.fixReadNode_PB)
        self.delGva_PB = QtWidgets.QPushButton(main_widget)
        self.delGva_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.delGva_PB.setObjectName("delGva_PB")
        self.horizontalLayout_18.addWidget(self.delGva_PB)
        self.newGva_PB = QtWidgets.QPushButton(main_widget)
        self.newGva_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.newGva_PB.setObjectName("newGva_PB")
        self.horizontalLayout_18.addWidget(self.newGva_PB)
        self.timeOff_PB = QtWidgets.QPushButton(main_widget)
        self.timeOff_PB.setObjectName("timeOff_PB")
        self.horizontalLayout_18.addWidget(self.timeOff_PB)
        self.vdbName_PB = QtWidgets.QPushButton(main_widget)
        self.vdbName_PB.setObjectName("vdbName_PB")
        self.horizontalLayout_18.addWidget(self.vdbName_PB)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem1)
        self.flag_commend_layout_3.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_18)
        self.verticalLayout.addLayout(self.flag_commend_layout_3)
        self.line = QtWidgets.QFrame(main_widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(main_widget)
        QtCore.QMetaObject.connectSlotsByName(main_widget)

    def retranslateUi(self, main_widget):
        main_widget.setWindowTitle(QtWidgets.QApplication.translate("main_widget", "Form", None, -1))
        self.targetVdb_label.setText(QtWidgets.QApplication.translate("main_widget", "Target VDB", None, -1))
        self.vdbFile_label.setText(QtWidgets.QApplication.translate("main_widget", "VDB File", None, -1))
        self.vdbBro_PB.setText(QtWidgets.QApplication.translate("main_widget", "...", None, -1))
        self.vdbOpen_PB.setText(QtWidgets.QApplication.translate("main_widget", "open", None, -1))
        self.vdbFileSet_PB.setText(QtWidgets.QApplication.translate("main_widget", "set", None, -1))
        self.vdbSg_label.setText(QtWidgets.QApplication.translate("main_widget", "VDB Shading Engine", None, -1))
        self.getSg_PB.setText(QtWidgets.QApplication.translate("main_widget", "get SG", None, -1))
        self.vdbSgSet_PB.setText(QtWidgets.QApplication.translate("main_widget", "set", None, -1))
        self.targetVdb_PB.setText(QtWidgets.QApplication.translate("main_widget", "get obj", None, -1))
        self.vdbView_label.setText(QtWidgets.QApplication.translate("main_widget", "VDB View", None, -1))
        self.renderAs_label.setText(QtWidgets.QApplication.translate("main_widget", "Render As", None, -1))
        self.renderAs_comboBox.setItemText(0, QtWidgets.QApplication.translate("main_widget", "Auto", None, -1))
        self.renderAs_comboBox.setItemText(1, QtWidgets.QApplication.translate("main_widget", "Level Sets", None, -1))
        self.renderAs_comboBox.setItemText(2, QtWidgets.QApplication.translate("main_widget", "Fog Volume", None, -1))
        self.leafNode_CB.setText(QtWidgets.QApplication.translate("main_widget", "Leaf Nodes", None, -1))
        self.activeVoxels_CB.setText(QtWidgets.QApplication.translate("main_widget", "Active Voxels", None, -1))
        self.surface_CB.setText(QtWidgets.QApplication.translate("main_widget", "Surface", None, -1))
        self.vdbSetView_PB.setText(QtWidgets.QApplication.translate("main_widget", "Set view", None, -1))
        self.setAllBox_PB.setText(QtWidgets.QApplication.translate("main_widget", "Set all box", None, -1))
        self.vdbView_label_2.setText(QtWidgets.QApplication.translate("main_widget", "Common", None, -1))
        self.fixReadNode_PB.setText(QtWidgets.QApplication.translate("main_widget", "Fix read node", None, -1))
        self.delGva_PB.setText(QtWidgets.QApplication.translate("main_widget", "Del GVA", None, -1))
        self.newGva_PB.setText(QtWidgets.QApplication.translate("main_widget", "New GVA", None, -1))
        self.timeOff_PB.setText(QtWidgets.QApplication.translate("main_widget", "Time off", None, -1))
        self.vdbName_PB.setText(QtWidgets.QApplication.translate("main_widget", "VDB rename", None, -1))

