# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/chihjung/Documents/maya/2017/scripts/ui/prmanToolsLighting.ui'
#
# Created: Thu Nov 30 09:25:29 2017
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_main_widget(object):
    def setupUi(self, main_widget):
        main_widget.setObjectName("main_widget")
        main_widget.resize(800, 600)
        self.main_layout = QtWidgets.QVBoxLayout(main_widget)
        self.main_layout.setSpacing(4)
        self.main_layout.setContentsMargins(4, 4, 4, 4)
        self.main_layout.setObjectName("main_layout")
        self.tools_layout = QtWidgets.QGridLayout()
        self.tools_layout.setContentsMargins(2, 2, 2, 2)
        self.tools_layout.setSpacing(4)
        self.tools_layout.setObjectName("tools_layout")
        self.creatMatteID_PB = QtWidgets.QPushButton(main_widget)
        self.creatMatteID_PB.setObjectName("creatMatteID_PB")
        self.tools_layout.addWidget(self.creatMatteID_PB, 1, 1, 1, 1)
        self.aoSettings_PB = QtWidgets.QPushButton(main_widget)
        self.aoSettings_PB.setObjectName("aoSettings_PB")
        self.tools_layout.addWidget(self.aoSettings_PB, 0, 3, 1, 1)
        self.motionVectorSetting_PB = QtWidgets.QPushButton(main_widget)
        self.motionVectorSetting_PB.setObjectName("motionVectorSetting_PB")
        self.tools_layout.addWidget(self.motionVectorSetting_PB, 0, 2, 1, 1)
        self.pxrMatteID_toShaders_PB = QtWidgets.QPushButton(main_widget)
        self.pxrMatteID_toShaders_PB.setObjectName("pxrMatteID_toShaders_PB")
        self.tools_layout.addWidget(self.pxrMatteID_toShaders_PB, 1, 2, 1, 1)
        self.matteNum_layout = QtWidgets.QHBoxLayout()
        self.matteNum_layout.setObjectName("matteNum_layout")
        self.matteNum_label = QtWidgets.QLabel(main_widget)
        self.matteNum_label.setObjectName("matteNum_label")
        self.matteNum_layout.addWidget(self.matteNum_label)
        self.matteNum_SB = QtWidgets.QSpinBox(main_widget)
        self.matteNum_SB.setMaximum(7)
        self.matteNum_SB.setObjectName("matteNum_SB")
        self.matteNum_layout.addWidget(self.matteNum_SB)
        self.tools_layout.addLayout(self.matteNum_layout, 1, 0, 1, 1)
        self.addSubD_PB = QtWidgets.QPushButton(main_widget)
        self.addSubD_PB.setObjectName("addSubD_PB")
        self.tools_layout.addWidget(self.addSubD_PB, 0, 0, 1, 1)
        self.deleteSubD_PB = QtWidgets.QPushButton(main_widget)
        self.deleteSubD_PB.setObjectName("deleteSubD_PB")
        self.tools_layout.addWidget(self.deleteSubD_PB, 0, 1, 1, 1)
        self.main_layout.addLayout(self.tools_layout)
        self.frame = QtWidgets.QFrame(main_widget)
        self.frame.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.main_layout.addWidget(self.frame)
        self.lightCheck_scrollArea = QtWidgets.QScrollArea(main_widget)
        self.lightCheck_scrollArea.setWidgetResizable(True)
        self.lightCheck_scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lightCheck_scrollArea.setObjectName("lightCheck_scrollArea")
        self.lightCheck_widget = QtWidgets.QWidget()
        self.lightCheck_widget.setGeometry(QtCore.QRect(0, 0, 790, 478))
        self.lightCheck_widget.setObjectName("lightCheck_widget")
        self.lightCheck_layout = QtWidgets.QVBoxLayout(self.lightCheck_widget)
        self.lightCheck_layout.setSpacing(4)
        self.lightCheck_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.lightCheck_layout.setContentsMargins(2, 2, 2, 2)
        self.lightCheck_layout.setObjectName("lightCheck_layout")
        self.lightCheck_scrollArea.setWidget(self.lightCheck_widget)
        self.main_layout.addWidget(self.lightCheck_scrollArea)
        self.infoBar_label = QtWidgets.QLabel(main_widget)
        self.infoBar_label.setAlignment(QtCore.Qt.AlignCenter)
        self.infoBar_label.setObjectName("infoBar_label")
        self.main_layout.addWidget(self.infoBar_label)
        self.lightSetting_layout = QtWidgets.QHBoxLayout()
        self.lightSetting_layout.setSpacing(4)
        self.lightSetting_layout.setContentsMargins(2, 2, 2, 2)
        self.lightSetting_layout.setObjectName("lightSetting_layout")
        self.checkLights_PB = QtWidgets.QPushButton(main_widget)
        self.checkLights_PB.setObjectName("checkLights_PB")
        self.lightSetting_layout.addWidget(self.checkLights_PB)
        self.beautySettings_PB = QtWidgets.QPushButton(main_widget)
        self.beautySettings_PB.setObjectName("beautySettings_PB")
        self.lightSetting_layout.addWidget(self.beautySettings_PB)
        self.denoiseSettings_PB = QtWidgets.QPushButton(main_widget)
        self.denoiseSettings_PB.setObjectName("denoiseSettings_PB")
        self.lightSetting_layout.addWidget(self.denoiseSettings_PB)
        self.main_layout.addLayout(self.lightSetting_layout)

        self.retranslateUi(main_widget)
        QtCore.QMetaObject.connectSlotsByName(main_widget)

    def retranslateUi(self, main_widget):
        main_widget.setWindowTitle(QtWidgets.QApplication.translate("main_widget", "Form", None, -1))
        self.creatMatteID_PB.setText(QtWidgets.QApplication.translate("main_widget", "create matteIDs", None, -1))
        self.aoSettings_PB.setText(QtWidgets.QApplication.translate("main_widget", "ao setting", None, -1))
        self.motionVectorSetting_PB.setText(QtWidgets.QApplication.translate("main_widget", "motion vector setting", None, -1))
        self.pxrMatteID_toShaders_PB.setText(QtWidgets.QApplication.translate("main_widget", "pxrMatteID to shaders", None, -1))
        self.matteNum_label.setText(QtWidgets.QApplication.translate("main_widget", "matte numbers :", None, -1))
        self.addSubD_PB.setText(QtWidgets.QApplication.translate("main_widget", "add subD", None, -1))
        self.deleteSubD_PB.setText(QtWidgets.QApplication.translate("main_widget", "delete subD", None, -1))
        self.infoBar_label.setText(QtWidgets.QApplication.translate("main_widget", "info bar", None, -1))
        self.checkLights_PB.setText(QtWidgets.QApplication.translate("main_widget", "Check lights", None, -1))
        self.beautySettings_PB.setText(QtWidgets.QApplication.translate("main_widget", "Beauty Settings", None, -1))
        self.denoiseSettings_PB.setText(QtWidgets.QApplication.translate("main_widget", "Denoise Settings", None, -1))

