# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/chihjung/Documents/maya/2018/scripts/ui/prmanR22_tools_objReplacement.ui'
#
# Created: Wed Feb 12 15:32:52 2020
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_main_widget(object):
    def setupUi(self, main_widget):
        main_widget.setObjectName("main_widget")
        main_widget.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(main_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.flag_commend_layout = QtWidgets.QFormLayout()
        self.flag_commend_layout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.flag_commend_layout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.flag_commend_layout.setContentsMargins(2, 2, 2, 2)
        self.flag_commend_layout.setHorizontalSpacing(8)
        self.flag_commend_layout.setVerticalSpacing(4)
        self.flag_commend_layout.setObjectName("flag_commend_layout")
        self.targetObj_label = QtWidgets.QLabel(main_widget)
        self.targetObj_label.setMinimumSize(QtCore.QSize(140, 0))
        self.targetObj_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.targetObj_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.targetObj_label.setObjectName("targetObj_label")
        self.flag_commend_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.targetObj_label)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.targetGetObj_LE = QtWidgets.QLineEdit(main_widget)
        self.targetGetObj_LE.setObjectName("targetGetObj_LE")
        self.horizontalLayout_11.addWidget(self.targetGetObj_LE)
        self.targetGetObj_PB = QtWidgets.QPushButton(main_widget)
        self.targetGetObj_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.targetGetObj_PB.setObjectName("targetGetObj_PB")
        self.horizontalLayout_11.addWidget(self.targetGetObj_PB)
        self.flag_commend_layout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.replacedWithObj_label = QtWidgets.QLabel(main_widget)
        self.replacedWithObj_label.setMinimumSize(QtCore.QSize(140, 0))
        self.replacedWithObj_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.replacedWithObj_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.replacedWithObj_label.setObjectName("replacedWithObj_label")
        self.flag_commend_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.replacedWithObj_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.replaceGetObj_LE = QtWidgets.QLineEdit(main_widget)
        self.replaceGetObj_LE.setObjectName("replaceGetObj_LE")
        self.horizontalLayout.addWidget(self.replaceGetObj_LE)
        self.replaceGetObj_PB = QtWidgets.QPushButton(main_widget)
        self.replaceGetObj_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.replaceGetObj_PB.setObjectName("replaceGetObj_PB")
        self.horizontalLayout.addWidget(self.replaceGetObj_PB)
        self.flag_commend_layout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.other_label = QtWidgets.QLabel(main_widget)
        self.other_label.setMinimumSize(QtCore.QSize(140, 0))
        self.other_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.other_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.other_label.setObjectName("other_label")
        self.flag_commend_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.other_label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dupDefaultRB = QtWidgets.QRadioButton(main_widget)
        self.dupDefaultRB.setChecked(True)
        self.dupDefaultRB.setObjectName("dupDefaultRB")
        self.horizontalLayout_3.addWidget(self.dupDefaultRB)
        self.dupInputGraph_RB = QtWidgets.QRadioButton(main_widget)
        self.dupInputGraph_RB.setObjectName("dupInputGraph_RB")
        self.horizontalLayout_3.addWidget(self.dupInputGraph_RB)
        self.dupInputConnections_RB = QtWidgets.QRadioButton(main_widget)
        self.dupInputConnections_RB.setObjectName("dupInputConnections_RB")
        self.horizontalLayout_3.addWidget(self.dupInputConnections_RB)
        self.duplicate_PB = QtWidgets.QPushButton(main_widget)
        self.duplicate_PB.setMinimumSize(QtCore.QSize(120, 0))
        self.duplicate_PB.setObjectName("duplicate_PB")
        self.horizontalLayout_3.addWidget(self.duplicate_PB)
        self.flag_commend_layout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.flag_commend_layout)
        self.line = QtWidgets.QFrame(main_widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.flag_commend_layout_2 = QtWidgets.QFormLayout()
        self.flag_commend_layout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.flag_commend_layout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.flag_commend_layout_2.setContentsMargins(2, 2, 2, 2)
        self.flag_commend_layout_2.setHorizontalSpacing(8)
        self.flag_commend_layout_2.setVerticalSpacing(4)
        self.flag_commend_layout_2.setObjectName("flag_commend_layout_2")
        self.targetVdb_label = QtWidgets.QLabel(main_widget)
        self.targetVdb_label.setMinimumSize(QtCore.QSize(140, 0))
        self.targetVdb_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.targetVdb_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.targetVdb_label.setObjectName("targetVdb_label")
        self.flag_commend_layout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.targetVdb_label)
        self.vdbFile_label = QtWidgets.QLabel(main_widget)
        self.vdbFile_label.setMinimumSize(QtCore.QSize(140, 0))
        self.vdbFile_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.vdbFile_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vdbFile_label.setObjectName("vdbFile_label")
        self.flag_commend_layout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.vdbFile_label)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(2)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.vdbFile_LE = QtWidgets.QLineEdit(main_widget)
        self.vdbFile_LE.setObjectName("vdbFile_LE")
        self.horizontalLayout_13.addWidget(self.vdbFile_LE)
        self.vdbBro_PB = QtWidgets.QPushButton(main_widget)
        self.vdbBro_PB.setMaximumSize(QtCore.QSize(20, 16777215))
        self.vdbBro_PB.setObjectName("vdbBro_PB")
        self.horizontalLayout_13.addWidget(self.vdbBro_PB)
        self.vdbOpen_PB = QtWidgets.QPushButton(main_widget)
        self.vdbOpen_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.vdbOpen_PB.setObjectName("vdbOpen_PB")
        self.horizontalLayout_13.addWidget(self.vdbOpen_PB)
        self.vdbFileSet_PB = QtWidgets.QPushButton(main_widget)
        self.vdbFileSet_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.vdbFileSet_PB.setObjectName("vdbFileSet_PB")
        self.horizontalLayout_13.addWidget(self.vdbFileSet_PB)
        self.flag_commend_layout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_13)
        self.vdbSg_label = QtWidgets.QLabel(main_widget)
        self.vdbSg_label.setMinimumSize(QtCore.QSize(140, 0))
        self.vdbSg_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.vdbSg_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vdbSg_label.setObjectName("vdbSg_label")
        self.flag_commend_layout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.vdbSg_label)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.vdbSg_LE = QtWidgets.QLineEdit(main_widget)
        self.vdbSg_LE.setText("")
        self.vdbSg_LE.setObjectName("vdbSg_LE")
        self.horizontalLayout_5.addWidget(self.vdbSg_LE)
        self.getSg_PB = QtWidgets.QPushButton(main_widget)
        self.getSg_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.getSg_PB.setObjectName("getSg_PB")
        self.horizontalLayout_5.addWidget(self.getSg_PB)
        self.vdbSgSet_PB = QtWidgets.QPushButton(main_widget)
        self.vdbSgSet_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.vdbSgSet_PB.setObjectName("vdbSgSet_PB")
        self.horizontalLayout_5.addWidget(self.vdbSgSet_PB)
        self.flag_commend_layout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(2)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.targetVdb_LE = QtWidgets.QLineEdit(main_widget)
        self.targetVdb_LE.setObjectName("targetVdb_LE")
        self.horizontalLayout_14.addWidget(self.targetVdb_LE)
        self.targetVdb_PB = QtWidgets.QPushButton(main_widget)
        self.targetVdb_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.targetVdb_PB.setObjectName("targetVdb_PB")
        self.horizontalLayout_14.addWidget(self.targetVdb_PB)
        self.flag_commend_layout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_14)
        self.verticalLayout.addLayout(self.flag_commend_layout_2)
        self.info_label = QtWidgets.QLabel(main_widget)
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setObjectName("info_label")
        self.verticalLayout.addWidget(self.info_label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(main_widget)
        QtCore.QMetaObject.connectSlotsByName(main_widget)

    def retranslateUi(self, main_widget):
        main_widget.setWindowTitle(QtWidgets.QApplication.translate("main_widget", "Form", None, -1))
        self.targetObj_label.setText(QtWidgets.QApplication.translate("main_widget", "Target Object", None, -1))
        self.targetGetObj_PB.setText(QtWidgets.QApplication.translate("main_widget", "get obj", None, -1))
        self.replacedWithObj_label.setText(QtWidgets.QApplication.translate("main_widget", "Replaced With Object", None, -1))
        self.replaceGetObj_PB.setText(QtWidgets.QApplication.translate("main_widget", "get obj", None, -1))
        self.other_label.setText(QtWidgets.QApplication.translate("main_widget", "Duplicate Object", None, -1))
        self.dupDefaultRB.setText(QtWidgets.QApplication.translate("main_widget", "default", None, -1))
        self.dupInputGraph_RB.setText(QtWidgets.QApplication.translate("main_widget", "duplicate input graph", None, -1))
        self.dupInputConnections_RB.setText(QtWidgets.QApplication.translate("main_widget", "duplicate input connections", None, -1))
        self.duplicate_PB.setText(QtWidgets.QApplication.translate("main_widget", "duplicate", None, -1))
        self.targetVdb_label.setText(QtWidgets.QApplication.translate("main_widget", "Target VDB", None, -1))
        self.vdbFile_label.setText(QtWidgets.QApplication.translate("main_widget", "VDB File", None, -1))
        self.vdbBro_PB.setText(QtWidgets.QApplication.translate("main_widget", "...", None, -1))
        self.vdbOpen_PB.setText(QtWidgets.QApplication.translate("main_widget", "open", None, -1))
        self.vdbFileSet_PB.setText(QtWidgets.QApplication.translate("main_widget", "set", None, -1))
        self.vdbSg_label.setText(QtWidgets.QApplication.translate("main_widget", "VDB Shading Engine", None, -1))
        self.getSg_PB.setText(QtWidgets.QApplication.translate("main_widget", "get SG", None, -1))
        self.vdbSgSet_PB.setText(QtWidgets.QApplication.translate("main_widget", "set", None, -1))
        self.targetVdb_PB.setText(QtWidgets.QApplication.translate("main_widget", "get obj", None, -1))
        self.info_label.setText(QtWidgets.QApplication.translate("main_widget", "info", None, -1))

