# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/chihjung/Documents/maya/2020/scripts/ui/prmanR22_tools_renderSetUp.ui',
# licensing of 'C:/Users/chihjung/Documents/maya/2020/scripts/ui/prmanR22_tools_renderSetUp.ui' applies.
#
# Created: Fri May 29 15:51:51 2020
#      by: pyside2-uic  running on PySide2 5.12.5
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_main_widget(object):
    def setupUi(self, main_widget):
        main_widget.setObjectName("main_widget")
        main_widget.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(main_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.flag_commend_layout = QtWidgets.QFormLayout()
        self.flag_commend_layout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.flag_commend_layout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.flag_commend_layout.setContentsMargins(2, 2, 2, 2)
        self.flag_commend_layout.setHorizontalSpacing(8)
        self.flag_commend_layout.setVerticalSpacing(4)
        self.flag_commend_layout.setObjectName("flag_commend_layout")
        self.serverJsonPath_label = QtWidgets.QLabel(main_widget)
        self.serverJsonPath_label.setMinimumSize(QtCore.QSize(140, 0))
        self.serverJsonPath_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.serverJsonPath_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.serverJsonPath_label.setObjectName("serverJsonPath_label")
        self.flag_commend_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.serverJsonPath_label)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.serverJsonPath_LE = QtWidgets.QLineEdit(main_widget)
        self.serverJsonPath_LE.setObjectName("serverJsonPath_LE")
        self.horizontalLayout_11.addWidget(self.serverJsonPath_LE)
        self.serverJsonPathBro_PB = QtWidgets.QPushButton(main_widget)
        self.serverJsonPathBro_PB.setMaximumSize(QtCore.QSize(20, 16777215))
        self.serverJsonPathBro_PB.setObjectName("serverJsonPathBro_PB")
        self.horizontalLayout_11.addWidget(self.serverJsonPathBro_PB)
        self.serverJsonOPen_PB = QtWidgets.QPushButton(main_widget)
        self.serverJsonOPen_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.serverJsonOPen_PB.setObjectName("serverJsonOPen_PB")
        self.horizontalLayout_11.addWidget(self.serverJsonOPen_PB)
        self.flag_commend_layout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.localJsonFile_label = QtWidgets.QLabel(main_widget)
        self.localJsonFile_label.setMinimumSize(QtCore.QSize(140, 0))
        self.localJsonFile_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.localJsonFile_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.localJsonFile_label.setObjectName("localJsonFile_label")
        self.flag_commend_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.localJsonFile_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.localJsonFile_LE = QtWidgets.QLineEdit(main_widget)
        self.localJsonFile_LE.setObjectName("localJsonFile_LE")
        self.horizontalLayout.addWidget(self.localJsonFile_LE)
        self.localJsonFile_Bro = QtWidgets.QPushButton(main_widget)
        self.localJsonFile_Bro.setMaximumSize(QtCore.QSize(20, 16777215))
        self.localJsonFile_Bro.setObjectName("localJsonFile_Bro")
        self.horizontalLayout.addWidget(self.localJsonFile_Bro)
        self.localJsonFile_Open = QtWidgets.QPushButton(main_widget)
        self.localJsonFile_Open.setMaximumSize(QtCore.QSize(100, 16777215))
        self.localJsonFile_Open.setObjectName("localJsonFile_Open")
        self.horizontalLayout.addWidget(self.localJsonFile_Open)
        self.flag_commend_layout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.matteId_label = QtWidgets.QLabel(main_widget)
        self.matteId_label.setMinimumSize(QtCore.QSize(140, 0))
        self.matteId_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.matteId_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matteId_label.setObjectName("matteId_label")
        self.flag_commend_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.matteId_label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addMatteIdAttr_PB = QtWidgets.QPushButton(main_widget)
        self.addMatteIdAttr_PB.setMinimumSize(QtCore.QSize(120, 0))
        self.addMatteIdAttr_PB.setObjectName("addMatteIdAttr_PB")
        self.horizontalLayout_3.addWidget(self.addMatteIdAttr_PB)
        self.pxrMatteIdSet_PB = QtWidgets.QPushButton(main_widget)
        self.pxrMatteIdSet_PB.setMinimumSize(QtCore.QSize(120, 0))
        self.pxrMatteIdSet_PB.setObjectName("pxrMatteIdSet_PB")
        self.horizontalLayout_3.addWidget(self.pxrMatteIdSet_PB)
        self.getNonMeshs_PB = QtWidgets.QPushButton(main_widget)
        self.getNonMeshs_PB.setMinimumSize(QtCore.QSize(120, 0))
        self.getNonMeshs_PB.setObjectName("getNonMeshs_PB")
        self.horizontalLayout_3.addWidget(self.getNonMeshs_PB)
        self.convertToShape_PB = QtWidgets.QPushButton(main_widget)
        self.convertToShape_PB.setMinimumSize(QtCore.QSize(120, 0))
        self.convertToShape_PB.setObjectName("convertToShape_PB")
        self.horizontalLayout_3.addWidget(self.convertToShape_PB)
        self.flag_commend_layout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.CreateAovLabel = QtWidgets.QLabel(main_widget)
        self.CreateAovLabel.setMinimumSize(QtCore.QSize(140, 0))
        self.CreateAovLabel.setMaximumSize(QtCore.QSize(140, 16777215))
        self.CreateAovLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.CreateAovLabel.setObjectName("CreateAovLabel")
        self.flag_commend_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.CreateAovLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.matteNums_label = QtWidgets.QLabel(main_widget)
        self.matteNums_label.setObjectName("matteNums_label")
        self.horizontalLayout_2.addWidget(self.matteNums_label)
        self.createMatteId_spinBox = QtWidgets.QSpinBox(main_widget)
        self.createMatteId_spinBox.setMaximum(7)
        self.createMatteId_spinBox.setObjectName("createMatteId_spinBox")
        self.horizontalLayout_2.addWidget(self.createMatteId_spinBox)
        self.createMatteId_PB = QtWidgets.QPushButton(main_widget)
        self.createMatteId_PB.setMinimumSize(QtCore.QSize(120, 0))
        self.createMatteId_PB.setObjectName("createMatteId_PB")
        self.horizontalLayout_2.addWidget(self.createMatteId_PB)
        self.createPnd_PB = QtWidgets.QPushButton(main_widget)
        self.createPnd_PB.setObjectName("createPnd_PB")
        self.horizontalLayout_2.addWidget(self.createPnd_PB)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.flag_commend_layout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.testt_label = QtWidgets.QLabel(main_widget)
        self.testt_label.setMinimumSize(QtCore.QSize(140, 0))
        self.testt_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.testt_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.testt_label.setObjectName("testt_label")
        self.flag_commend_layout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.testt_label)
        self.test_layout = QtWidgets.QHBoxLayout()
        self.test_layout.setSpacing(2)
        self.test_layout.setObjectName("test_layout")
        self.test_PB = QtWidgets.QPushButton(main_widget)
        self.test_PB.setObjectName("test_PB")
        self.test_layout.addWidget(self.test_PB)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.test_layout.addItem(spacerItem1)
        self.flag_commend_layout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.test_layout)
        self.lightGrpAov_label = QtWidgets.QLabel(main_widget)
        self.lightGrpAov_label.setMinimumSize(QtCore.QSize(140, 0))
        self.lightGrpAov_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.lightGrpAov_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lightGrpAov_label.setObjectName("lightGrpAov_label")
        self.flag_commend_layout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lightGrpAov_label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lightGrp_comboBox = QtWidgets.QComboBox(main_widget)
        self.lightGrp_comboBox.setObjectName("lightGrp_comboBox")
        self.horizontalLayout_4.addWidget(self.lightGrp_comboBox)
        self.createBeauty_PB = QtWidgets.QPushButton(main_widget)
        self.createBeauty_PB.setObjectName("createBeauty_PB")
        self.horizontalLayout_4.addWidget(self.createBeauty_PB)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.flag_commend_layout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.flag_commend_layout)
        self.line = QtWidgets.QFrame(main_widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.info_label = QtWidgets.QLabel(main_widget)
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setObjectName("info_label")
        self.verticalLayout.addWidget(self.info_label)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)

        self.retranslateUi(main_widget)
        QtCore.QMetaObject.connectSlotsByName(main_widget)

    def retranslateUi(self, main_widget):
        main_widget.setWindowTitle(QtWidgets.QApplication.translate("main_widget", "Form", None, -1))
        self.serverJsonPath_label.setText(QtWidgets.QApplication.translate("main_widget", "Server Json Path", None, -1))
        self.serverJsonPathBro_PB.setText(QtWidgets.QApplication.translate("main_widget", "...", None, -1))
        self.serverJsonOPen_PB.setText(QtWidgets.QApplication.translate("main_widget", "open", None, -1))
        self.localJsonFile_label.setText(QtWidgets.QApplication.translate("main_widget", "local Json File", None, -1))
        self.localJsonFile_Bro.setText(QtWidgets.QApplication.translate("main_widget", "...", None, -1))
        self.localJsonFile_Open.setText(QtWidgets.QApplication.translate("main_widget", "open", None, -1))
        self.matteId_label.setText(QtWidgets.QApplication.translate("main_widget", "Matte ID", None, -1))
        self.addMatteIdAttr_PB.setText(QtWidgets.QApplication.translate("main_widget", "Add MatteID Attr", None, -1))
        self.pxrMatteIdSet_PB.setText(QtWidgets.QApplication.translate("main_widget", "pxrMatteID Sets", None, -1))
        self.getNonMeshs_PB.setText(QtWidgets.QApplication.translate("main_widget", "Get Non-Meshs", None, -1))
        self.convertToShape_PB.setText(QtWidgets.QApplication.translate("main_widget", "Convert  To Shape", None, -1))
        self.CreateAovLabel.setText(QtWidgets.QApplication.translate("main_widget", "Common AOV", None, -1))
        self.matteNums_label.setText(QtWidgets.QApplication.translate("main_widget", "matte numbers", None, -1))
        self.createMatteId_PB.setText(QtWidgets.QApplication.translate("main_widget", "Create MatteId", None, -1))
        self.createPnd_PB.setText(QtWidgets.QApplication.translate("main_widget", "Create P.N.D", None, -1))
        self.testt_label.setText(QtWidgets.QApplication.translate("main_widget", "test _data", None, -1))
        self.test_PB.setText(QtWidgets.QApplication.translate("main_widget", "test", None, -1))
        self.lightGrpAov_label.setText(QtWidgets.QApplication.translate("main_widget", "Light Group AOV", None, -1))
        self.createBeauty_PB.setText(QtWidgets.QApplication.translate("main_widget", "Create Beauty", None, -1))
        self.info_label.setText(QtWidgets.QApplication.translate("main_widget", "info", None, -1))

