# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/chihjung/Documents/maya/2020/scripts/ui/prmanR22_tools_renderSets.ui',
# licensing of 'C:/Users/chihjung/Documents/maya/2020/scripts/ui/prmanR22_tools_renderSets.ui' applies.
#
# Created: Fri May 29 15:51:51 2020
#      by: pyside2-uic  running on PySide2 5.12.5
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_main_widget(object):
    def setupUi(self, main_widget):
        main_widget.setObjectName("main_widget")
        main_widget.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(main_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.flag_commend_layout = QtWidgets.QFormLayout()
        self.flag_commend_layout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.flag_commend_layout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.flag_commend_layout.setContentsMargins(2, 2, 2, 2)
        self.flag_commend_layout.setHorizontalSpacing(8)
        self.flag_commend_layout.setVerticalSpacing(4)
        self.flag_commend_layout.setObjectName("flag_commend_layout")
        self.subdivision_label = QtWidgets.QLabel(main_widget)
        self.subdivision_label.setMinimumSize(QtCore.QSize(140, 0))
        self.subdivision_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.subdivision_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.subdivision_label.setObjectName("subdivision_label")
        self.flag_commend_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.subdivision_label)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.subDivisionOn_RB = QtWidgets.QRadioButton(main_widget)
        self.subDivisionOn_RB.setObjectName("subDivisionOn_RB")
        self.horizontalLayout_11.addWidget(self.subDivisionOn_RB)
        self.subDivisionOff_RB = QtWidgets.QRadioButton(main_widget)
        self.subDivisionOff_RB.setObjectName("subDivisionOff_RB")
        self.horizontalLayout_11.addWidget(self.subDivisionOff_RB)
        self.subdivisionSet_PB = QtWidgets.QPushButton(main_widget)
        self.subdivisionSet_PB.setMaximumSize(QtCore.QSize(150, 16777215))
        self.subdivisionSet_PB.setObjectName("subdivisionSet_PB")
        self.horizontalLayout_11.addWidget(self.subdivisionSet_PB)
        self.subdivisionSelect_PB = QtWidgets.QPushButton(main_widget)
        self.subdivisionSelect_PB.setObjectName("subdivisionSelect_PB")
        self.horizontalLayout_11.addWidget(self.subdivisionSelect_PB)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.flag_commend_layout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.matteId_label = QtWidgets.QLabel(main_widget)
        self.matteId_label.setMinimumSize(QtCore.QSize(140, 0))
        self.matteId_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.matteId_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matteId_label.setObjectName("matteId_label")
        self.flag_commend_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.matteId_label)
        self.exportName_layout = QtWidgets.QHBoxLayout()
        self.exportName_layout.setSpacing(2)
        self.exportName_layout.setObjectName("exportName_layout")
        self.matteIdNum_combobox = QtWidgets.QComboBox(main_widget)
        self.matteIdNum_combobox.setMinimumSize(QtCore.QSize(80, 0))
        self.matteIdNum_combobox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.matteIdNum_combobox.setObjectName("matteIdNum_combobox")
        self.matteIdNum_combobox.addItem("")
        self.matteIdNum_combobox.addItem("")
        self.matteIdNum_combobox.addItem("")
        self.matteIdNum_combobox.addItem("")
        self.matteIdNum_combobox.addItem("")
        self.matteIdNum_combobox.addItem("")
        self.matteIdNum_combobox.addItem("")
        self.matteIdNum_combobox.addItem("")
        self.exportName_layout.addWidget(self.matteIdNum_combobox)
        self.matteIdRed_RB = QtWidgets.QRadioButton(main_widget)
        self.matteIdRed_RB.setIconSize(QtCore.QSize(16, 16))
        self.matteIdRed_RB.setObjectName("matteIdRed_RB")
        self.exportName_layout.addWidget(self.matteIdRed_RB)
        self.matteIdGreen_RB = QtWidgets.QRadioButton(main_widget)
        self.matteIdGreen_RB.setObjectName("matteIdGreen_RB")
        self.exportName_layout.addWidget(self.matteIdGreen_RB)
        self.matteIdBlue_RB = QtWidgets.QRadioButton(main_widget)
        self.matteIdBlue_RB.setObjectName("matteIdBlue_RB")
        self.exportName_layout.addWidget(self.matteIdBlue_RB)
        self.matteIdAttach_PB = QtWidgets.QPushButton(main_widget)
        self.matteIdAttach_PB.setMinimumSize(QtCore.QSize(80, 0))
        self.matteIdAttach_PB.setMaximumSize(QtCore.QSize(80, 16777215))
        self.matteIdAttach_PB.setObjectName("matteIdAttach_PB")
        self.exportName_layout.addWidget(self.matteIdAttach_PB)
        self.matteIdDetach_PB = QtWidgets.QPushButton(main_widget)
        self.matteIdDetach_PB.setMinimumSize(QtCore.QSize(80, 0))
        self.matteIdDetach_PB.setMaximumSize(QtCore.QSize(80, 16777215))
        self.matteIdDetach_PB.setObjectName("matteIdDetach_PB")
        self.exportName_layout.addWidget(self.matteIdDetach_PB)
        self.matteIdSelect_PB = QtWidgets.QPushButton(main_widget)
        self.matteIdSelect_PB.setMinimumSize(QtCore.QSize(100, 0))
        self.matteIdSelect_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.matteIdSelect_PB.setObjectName("matteIdSelect_PB")
        self.exportName_layout.addWidget(self.matteIdSelect_PB)
        self.matteIdPxrMatteId_PB = QtWidgets.QPushButton(main_widget)
        self.matteIdPxrMatteId_PB.setMinimumSize(QtCore.QSize(100, 0))
        self.matteIdPxrMatteId_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.matteIdPxrMatteId_PB.setObjectName("matteIdPxrMatteId_PB")
        self.exportName_layout.addWidget(self.matteIdPxrMatteId_PB)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.exportName_layout.addItem(spacerItem1)
        self.flag_commend_layout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.exportName_layout)
        self.label = QtWidgets.QLabel(main_widget)
        self.label.setMinimumSize(QtCore.QSize(140, 0))
        self.label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.flag_commend_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.commonAttr_layout = QtWidgets.QHBoxLayout()
        self.commonAttr_layout.setSpacing(2)
        self.commonAttr_layout.setObjectName("commonAttr_layout")
        self.commonAttr_comboBox = QtWidgets.QComboBox(main_widget)
        self.commonAttr_comboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.commonAttr_comboBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.commonAttr_comboBox.setObjectName("commonAttr_comboBox")
        self.commonAttr_comboBox.addItem("")
        self.commonAttr_comboBox.addItem("")
        self.commonAttr_comboBox.addItem("")
        self.commonAttr_comboBox.addItem("")
        self.commonAttr_comboBox.addItem("")
        self.commonAttr_layout.addWidget(self.commonAttr_comboBox)
        self.commonAttrOn_RP = QtWidgets.QRadioButton(main_widget)
        self.commonAttrOn_RP.setMinimumSize(QtCore.QSize(40, 0))
        self.commonAttrOn_RP.setMaximumSize(QtCore.QSize(40, 16777215))
        self.commonAttrOn_RP.setObjectName("commonAttrOn_RP")
        self.commonAttr_layout.addWidget(self.commonAttrOn_RP)
        self.commonAttrOff_RP = QtWidgets.QRadioButton(main_widget)
        self.commonAttrOff_RP.setMinimumSize(QtCore.QSize(40, 0))
        self.commonAttrOff_RP.setMaximumSize(QtCore.QSize(40, 16777215))
        self.commonAttrOff_RP.setObjectName("commonAttrOff_RP")
        self.commonAttr_layout.addWidget(self.commonAttrOff_RP)
        self.commonAttrInherit_RP = QtWidgets.QRadioButton(main_widget)
        self.commonAttrInherit_RP.setMinimumSize(QtCore.QSize(60, 0))
        self.commonAttrInherit_RP.setMaximumSize(QtCore.QSize(60, 16777215))
        self.commonAttrInherit_RP.setObjectName("commonAttrInherit_RP")
        self.commonAttr_layout.addWidget(self.commonAttrInherit_RP)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.commonAttr_layout.addItem(spacerItem2)
        self.flag_commend_layout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.commonAttr_layout)
        self.testt_label = QtWidgets.QLabel(main_widget)
        self.testt_label.setMinimumSize(QtCore.QSize(140, 0))
        self.testt_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.testt_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.testt_label.setObjectName("testt_label")
        self.flag_commend_layout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.testt_label)
        self.test_layout = QtWidgets.QHBoxLayout()
        self.test_layout.setSpacing(2)
        self.test_layout.setObjectName("test_layout")
        self.test_PB = QtWidgets.QPushButton(main_widget)
        self.test_PB.setObjectName("test_PB")
        self.test_layout.addWidget(self.test_PB)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.test_layout.addItem(spacerItem3)
        self.flag_commend_layout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.test_layout)
        self.attrEdit_label = QtWidgets.QLabel(main_widget)
        self.attrEdit_label.setMinimumSize(QtCore.QSize(140, 0))
        self.attrEdit_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.attrEdit_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.attrEdit_label.setObjectName("attrEdit_label")
        self.flag_commend_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.attrEdit_label)
        self.attrEdit_layout = QtWidgets.QHBoxLayout()
        self.attrEdit_layout.setSpacing(2)
        self.attrEdit_layout.setObjectName("attrEdit_layout")
        self.commonAttrSet_PB = QtWidgets.QPushButton(main_widget)
        self.commonAttrSet_PB.setMinimumSize(QtCore.QSize(60, 0))
        self.commonAttrSet_PB.setMaximumSize(QtCore.QSize(60, 16777215))
        self.commonAttrSet_PB.setObjectName("commonAttrSet_PB")
        self.attrEdit_layout.addWidget(self.commonAttrSet_PB)
        self.commonAttrOverrideSet_PB = QtWidgets.QPushButton(main_widget)
        self.commonAttrOverrideSet_PB.setMinimumSize(QtCore.QSize(100, 0))
        self.commonAttrOverrideSet_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.commonAttrOverrideSet_PB.setObjectName("commonAttrOverrideSet_PB")
        self.attrEdit_layout.addWidget(self.commonAttrOverrideSet_PB)
        self.commonAttrOverrideRemove_PB = QtWidgets.QPushButton(main_widget)
        self.commonAttrOverrideRemove_PB.setMinimumSize(QtCore.QSize(100, 0))
        self.commonAttrOverrideRemove_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.commonAttrOverrideRemove_PB.setObjectName("commonAttrOverrideRemove_PB")
        self.attrEdit_layout.addWidget(self.commonAttrOverrideRemove_PB)
        self.commonAttrSelectObj_PB = QtWidgets.QPushButton(main_widget)
        self.commonAttrSelectObj_PB.setMinimumSize(QtCore.QSize(100, 0))
        self.commonAttrSelectObj_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.commonAttrSelectObj_PB.setObjectName("commonAttrSelectObj_PB")
        self.attrEdit_layout.addWidget(self.commonAttrSelectObj_PB)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.attrEdit_layout.addItem(spacerItem4)
        self.flag_commend_layout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.attrEdit_layout)
        self.label_2 = QtWidgets.QLabel(main_widget)
        self.label_2.setMinimumSize(QtCore.QSize(140, 0))
        self.label_2.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.flag_commend_layout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hideInRlHide_PB = QtWidgets.QPushButton(main_widget)
        self.hideInRlHide_PB.setObjectName("hideInRlHide_PB")
        self.horizontalLayout.addWidget(self.hideInRlHide_PB)
        self.hideInRlSelect_PB = QtWidgets.QPushButton(main_widget)
        self.hideInRlSelect_PB.setObjectName("hideInRlSelect_PB")
        self.horizontalLayout.addWidget(self.hideInRlSelect_PB)
        self.hideInRlDetach_PB = QtWidgets.QPushButton(main_widget)
        self.hideInRlDetach_PB.setObjectName("hideInRlDetach_PB")
        self.horizontalLayout.addWidget(self.hideInRlDetach_PB)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.flag_commend_layout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.verticalLayout.addLayout(self.flag_commend_layout)
        self.line = QtWidgets.QFrame(main_widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.info_label = QtWidgets.QLabel(main_widget)
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setObjectName("info_label")
        self.verticalLayout.addWidget(self.info_label)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)

        self.retranslateUi(main_widget)
        QtCore.QMetaObject.connectSlotsByName(main_widget)

    def retranslateUi(self, main_widget):
        main_widget.setWindowTitle(QtWidgets.QApplication.translate("main_widget", "Form", None, -1))
        self.subdivision_label.setText(QtWidgets.QApplication.translate("main_widget", "Subdivision", None, -1))
        self.subDivisionOn_RB.setText(QtWidgets.QApplication.translate("main_widget", "on", None, -1))
        self.subDivisionOff_RB.setText(QtWidgets.QApplication.translate("main_widget", "off", None, -1))
        self.subdivisionSet_PB.setText(QtWidgets.QApplication.translate("main_widget", "set", None, -1))
        self.subdivisionSelect_PB.setText(QtWidgets.QApplication.translate("main_widget", "select obj", None, -1))
        self.matteId_label.setText(QtWidgets.QApplication.translate("main_widget", "Matte ID", None, -1))
        self.matteIdNum_combobox.setItemText(0, QtWidgets.QApplication.translate("main_widget", "MatteID0", None, -1))
        self.matteIdNum_combobox.setItemText(1, QtWidgets.QApplication.translate("main_widget", "MatteID1", None, -1))
        self.matteIdNum_combobox.setItemText(2, QtWidgets.QApplication.translate("main_widget", "MatteID2", None, -1))
        self.matteIdNum_combobox.setItemText(3, QtWidgets.QApplication.translate("main_widget", "MatteID3", None, -1))
        self.matteIdNum_combobox.setItemText(4, QtWidgets.QApplication.translate("main_widget", "MatteID4", None, -1))
        self.matteIdNum_combobox.setItemText(5, QtWidgets.QApplication.translate("main_widget", "MatteID5", None, -1))
        self.matteIdNum_combobox.setItemText(6, QtWidgets.QApplication.translate("main_widget", "MatteID6", None, -1))
        self.matteIdNum_combobox.setItemText(7, QtWidgets.QApplication.translate("main_widget", "MatteID7", None, -1))
        self.matteIdRed_RB.setText(QtWidgets.QApplication.translate("main_widget", "■", None, -1))
        self.matteIdGreen_RB.setText(QtWidgets.QApplication.translate("main_widget", "■", None, -1))
        self.matteIdBlue_RB.setText(QtWidgets.QApplication.translate("main_widget", "■", None, -1))
        self.matteIdAttach_PB.setText(QtWidgets.QApplication.translate("main_widget", "attach", None, -1))
        self.matteIdDetach_PB.setText(QtWidgets.QApplication.translate("main_widget", "detach", None, -1))
        self.matteIdSelect_PB.setText(QtWidgets.QApplication.translate("main_widget", "select obj", None, -1))
        self.matteIdPxrMatteId_PB.setText(QtWidgets.QApplication.translate("main_widget", "pxrMatteID sets", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("main_widget", "Attribute Selection", None, -1))
        self.commonAttr_comboBox.setItemText(0, QtWidgets.QApplication.translate("main_widget", "Camera Visibility", None, -1))
        self.commonAttr_comboBox.setItemText(1, QtWidgets.QApplication.translate("main_widget", "Indirect Visibility", None, -1))
        self.commonAttr_comboBox.setItemText(2, QtWidgets.QApplication.translate("main_widget", "Transmission Visibility", None, -1))
        self.commonAttr_comboBox.setItemText(3, QtWidgets.QApplication.translate("main_widget", "Matte Object", None, -1))
        self.commonAttr_comboBox.setItemText(4, QtWidgets.QApplication.translate("main_widget", "Hold Out", None, -1))
        self.commonAttrOn_RP.setText(QtWidgets.QApplication.translate("main_widget", "on", None, -1))
        self.commonAttrOff_RP.setText(QtWidgets.QApplication.translate("main_widget", "off", None, -1))
        self.commonAttrInherit_RP.setText(QtWidgets.QApplication.translate("main_widget", "inherit", None, -1))
        self.testt_label.setText(QtWidgets.QApplication.translate("main_widget", "test _data", None, -1))
        self.test_PB.setText(QtWidgets.QApplication.translate("main_widget", "test", None, -1))
        self.attrEdit_label.setText(QtWidgets.QApplication.translate("main_widget", " Attribute Edit", None, -1))
        self.commonAttrSet_PB.setText(QtWidgets.QApplication.translate("main_widget", "set", None, -1))
        self.commonAttrOverrideSet_PB.setText(QtWidgets.QApplication.translate("main_widget", "override set", None, -1))
        self.commonAttrOverrideRemove_PB.setText(QtWidgets.QApplication.translate("main_widget", "remove override", None, -1))
        self.commonAttrSelectObj_PB.setText(QtWidgets.QApplication.translate("main_widget", "select obj", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("main_widget", "Hide in RL", None, -1))
        self.hideInRlHide_PB.setText(QtWidgets.QApplication.translate("main_widget", "hide", None, -1))
        self.hideInRlSelect_PB.setText(QtWidgets.QApplication.translate("main_widget", "select", None, -1))
        self.hideInRlDetach_PB.setText(QtWidgets.QApplication.translate("main_widget", "detach", None, -1))
        self.info_label.setText(QtWidgets.QApplication.translate("main_widget", "info", None, -1))

