# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/chihjung/Documents/maya/2017/scripts/ui/prmanDenoiseToolsMergeEXR.ui'
#
# Created: Thu Nov 30 09:25:29 2017
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_main_widget(object):
    def setupUi(self, main_widget):
        main_widget.setObjectName("main_widget")
        main_widget.resize(800, 541)
        self.verticalLayout = QtWidgets.QVBoxLayout(main_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.exrInfo_layout = QtWidgets.QFormLayout()
        self.exrInfo_layout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.exrInfo_layout.setContentsMargins(2, 2, 2, 2)
        self.exrInfo_layout.setSpacing(4)
        self.exrInfo_layout.setObjectName("exrInfo_layout")
        self.filterExr_label = QtWidgets.QLabel(main_widget)
        self.filterExr_label.setMinimumSize(QtCore.QSize(0, 0))
        self.filterExr_label.setMaximumSize(QtCore.QSize(120, 16777215))
        self.filterExr_label.setObjectName("filterExr_label")
        self.exrInfo_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.filterExr_label)
        self.filterExr_layout = QtWidgets.QHBoxLayout()
        self.filterExr_layout.setSpacing(2)
        self.filterExr_layout.setObjectName("filterExr_layout")
        self.filterExr_LE = QtWidgets.QLineEdit(main_widget)
        self.filterExr_LE.setObjectName("filterExr_LE")
        self.filterExr_layout.addWidget(self.filterExr_LE)
        self.filterExrBro_PB = QtWidgets.QPushButton(main_widget)
        self.filterExrBro_PB.setMaximumSize(QtCore.QSize(20, 16777215))
        self.filterExrBro_PB.setObjectName("filterExrBro_PB")
        self.filterExr_layout.addWidget(self.filterExrBro_PB)
        self.filterExrOpen_PB = QtWidgets.QPushButton(main_widget)
        self.filterExrOpen_PB.setObjectName("filterExrOpen_PB")
        self.filterExr_layout.addWidget(self.filterExrOpen_PB)
        self.exrInfo_layout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.filterExr_layout)
        self.baseName_label = QtWidgets.QLabel(main_widget)
        self.baseName_label.setMinimumSize(QtCore.QSize(0, 0))
        self.baseName_label.setMaximumSize(QtCore.QSize(120, 16777215))
        self.baseName_label.setObjectName("baseName_label")
        self.exrInfo_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.baseName_label)
        self.baseName_LE = QtWidgets.QLineEdit(main_widget)
        self.baseName_LE.setMinimumSize(QtCore.QSize(200, 0))
        self.baseName_LE.setMaximumSize(QtCore.QSize(200, 16777215))
        self.baseName_LE.setObjectName("baseName_LE")
        self.exrInfo_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.baseName_LE)
        self.aovLightGrpName_label = QtWidgets.QLabel(main_widget)
        self.aovLightGrpName_label.setMinimumSize(QtCore.QSize(0, 0))
        self.aovLightGrpName_label.setMaximumSize(QtCore.QSize(120, 16777215))
        self.aovLightGrpName_label.setObjectName("aovLightGrpName_label")
        self.exrInfo_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.aovLightGrpName_label)
        self.aovLightGrpName_LE = QtWidgets.QLineEdit(main_widget)
        self.aovLightGrpName_LE.setMinimumSize(QtCore.QSize(200, 0))
        self.aovLightGrpName_LE.setMaximumSize(QtCore.QSize(200, 16777215))
        self.aovLightGrpName_LE.setObjectName("aovLightGrpName_LE")
        self.exrInfo_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.aovLightGrpName_LE)
        self.frameRange_label = QtWidgets.QLabel(main_widget)
        self.frameRange_label.setMinimumSize(QtCore.QSize(0, 0))
        self.frameRange_label.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frameRange_label.setObjectName("frameRange_label")
        self.exrInfo_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.frameRange_label)
        self.frameRange_layout = QtWidgets.QHBoxLayout()
        self.frameRange_layout.setSpacing(2)
        self.frameRange_layout.setContentsMargins(0, 0, 0, 0)
        self.frameRange_layout.setObjectName("frameRange_layout")
        self.frameRangeStart_label = QtWidgets.QLabel(main_widget)
        self.frameRangeStart_label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frameRangeStart_label.setObjectName("frameRangeStart_label")
        self.frameRange_layout.addWidget(self.frameRangeStart_label)
        self.frameRangeStart_LE = QtWidgets.QLineEdit(main_widget)
        self.frameRangeStart_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frameRangeStart_LE.setObjectName("frameRangeStart_LE")
        self.frameRange_layout.addWidget(self.frameRangeStart_LE)
        self.frameRangeEnd_label = QtWidgets.QLabel(main_widget)
        self.frameRangeEnd_label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frameRangeEnd_label.setObjectName("frameRangeEnd_label")
        self.frameRange_layout.addWidget(self.frameRangeEnd_label)
        self.frameRangeEnd_LE = QtWidgets.QLineEdit(main_widget)
        self.frameRangeEnd_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frameRangeEnd_LE.setObjectName("frameRangeEnd_LE")
        self.frameRange_layout.addWidget(self.frameRangeEnd_LE)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.frameRange_layout.addItem(spacerItem)
        self.exrInfo_layout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.frameRange_layout)
        self.checkChannel_label = QtWidgets.QLabel(main_widget)
        self.checkChannel_label.setMinimumSize(QtCore.QSize(0, 0))
        self.checkChannel_label.setMaximumSize(QtCore.QSize(120, 16777215))
        self.checkChannel_label.setObjectName("checkChannel_label")
        self.exrInfo_layout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.checkChannel_label)
        self.checkChannel_layout = QtWidgets.QHBoxLayout()
        self.checkChannel_layout.setSpacing(2)
        self.checkChannel_layout.setObjectName("checkChannel_layout")
        self.checkChannel_PB = QtWidgets.QPushButton(main_widget)
        self.checkChannel_PB.setObjectName("checkChannel_PB")
        self.checkChannel_layout.addWidget(self.checkChannel_PB)
        self.checkChannel_LE = QtWidgets.QLineEdit(main_widget)
        self.checkChannel_LE.setObjectName("checkChannel_LE")
        self.checkChannel_layout.addWidget(self.checkChannel_LE)
        self.exrInfo_layout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.checkChannel_layout)
        self.final_name_label = QtWidgets.QLabel(main_widget)
        self.final_name_label.setMinimumSize(QtCore.QSize(0, 0))
        self.final_name_label.setMaximumSize(QtCore.QSize(120, 16777215))
        self.final_name_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.final_name_label.setObjectName("final_name_label")
        self.exrInfo_layout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.final_name_label)
        self.final_name_LE = QtWidgets.QLineEdit(main_widget)
        self.final_name_LE.setObjectName("final_name_LE")
        self.exrInfo_layout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.final_name_LE)
        self.output_dir_label = QtWidgets.QLabel(main_widget)
        self.output_dir_label.setMinimumSize(QtCore.QSize(0, 0))
        self.output_dir_label.setMaximumSize(QtCore.QSize(120, 16777215))
        self.output_dir_label.setObjectName("output_dir_label")
        self.exrInfo_layout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.output_dir_label)
        self.outDir_layout = QtWidgets.QHBoxLayout()
        self.outDir_layout.setSpacing(2)
        self.outDir_layout.setObjectName("outDir_layout")
        self.outDir_LE = QtWidgets.QLineEdit(main_widget)
        self.outDir_LE.setObjectName("outDir_LE")
        self.outDir_layout.addWidget(self.outDir_LE)
        self.outDirBro_PB = QtWidgets.QPushButton(main_widget)
        self.outDirBro_PB.setMaximumSize(QtCore.QSize(20, 16777215))
        self.outDirBro_PB.setObjectName("outDirBro_PB")
        self.outDir_layout.addWidget(self.outDirBro_PB)
        self.outDirOpen_PB = QtWidgets.QPushButton(main_widget)
        self.outDirOpen_PB.setObjectName("outDirOpen_PB")
        self.outDir_layout.addWidget(self.outDirOpen_PB)
        self.exrInfo_layout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.outDir_layout)
        self.verticalLayout.addLayout(self.exrInfo_layout)
        self.info_textEdit = QtWidgets.QTextEdit(main_widget)
        self.info_textEdit.setReadOnly(True)
        self.info_textEdit.setObjectName("info_textEdit")
        self.verticalLayout.addWidget(self.info_textEdit)
        self.progressBar = QtWidgets.QProgressBar(main_widget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.runMerge_layout = QtWidgets.QHBoxLayout()
        self.runMerge_layout.setSpacing(4)
        self.runMerge_layout.setContentsMargins(2, 2, 2, 2)
        self.runMerge_layout.setObjectName("runMerge_layout")
        self.runMerge_PU = QtWidgets.QPushButton(main_widget)
        self.runMerge_PU.setObjectName("runMerge_PU")
        self.runMerge_layout.addWidget(self.runMerge_PU)
        self.stop_PU = QtWidgets.QPushButton(main_widget)
        self.stop_PU.setObjectName("stop_PU")
        self.runMerge_layout.addWidget(self.stop_PU)
        self.verticalLayout.addLayout(self.runMerge_layout)

        self.retranslateUi(main_widget)
        QtCore.QMetaObject.connectSlotsByName(main_widget)

    def retranslateUi(self, main_widget):
        main_widget.setWindowTitle(QtWidgets.QApplication.translate("main_widget", "Form", None, -1))
        self.filterExr_label.setText(QtWidgets.QApplication.translate("main_widget", "filter exr", None, -1))
        self.filterExrBro_PB.setText(QtWidgets.QApplication.translate("main_widget", "...", None, -1))
        self.filterExrOpen_PB.setText(QtWidgets.QApplication.translate("main_widget", "open", None, -1))
        self.baseName_label.setText(QtWidgets.QApplication.translate("main_widget", "base name", None, -1))
        self.aovLightGrpName_label.setText(QtWidgets.QApplication.translate("main_widget", "AOV light grp name", None, -1))
        self.frameRange_label.setText(QtWidgets.QApplication.translate("main_widget", "frame range", None, -1))
        self.frameRangeStart_label.setText(QtWidgets.QApplication.translate("main_widget", "start", None, -1))
        self.frameRangeStart_LE.setText(QtWidgets.QApplication.translate("main_widget", "0001", None, -1))
        self.frameRangeEnd_label.setText(QtWidgets.QApplication.translate("main_widget", "end", None, -1))
        self.frameRangeEnd_LE.setText(QtWidgets.QApplication.translate("main_widget", "0001", None, -1))
        self.checkChannel_label.setText(QtWidgets.QApplication.translate("main_widget", "channel of images", None, -1))
        self.checkChannel_PB.setText(QtWidgets.QApplication.translate("main_widget", "check", None, -1))
        self.final_name_label.setText(QtWidgets.QApplication.translate("main_widget", "final name", None, -1))
        self.final_name_LE.setText(QtWidgets.QApplication.translate("main_widget", "beauty", None, -1))
        self.output_dir_label.setText(QtWidgets.QApplication.translate("main_widget", "output directory", None, -1))
        self.outDirBro_PB.setText(QtWidgets.QApplication.translate("main_widget", "...", None, -1))
        self.outDirOpen_PB.setText(QtWidgets.QApplication.translate("main_widget", "open", None, -1))
        self.runMerge_PU.setText(QtWidgets.QApplication.translate("main_widget", "run merge", None, -1))
        self.stop_PU.setText(QtWidgets.QApplication.translate("main_widget", "stop", None, -1))

