# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/chihjung/Documents/maya/2023/scripts/ui/prmanR22_tools_objEdit.ui',
# licensing of 'C:/Users/chihjung/Documents/maya/2023/scripts/ui/prmanR22_tools_objEdit.ui' applies.
#
# Created: Tue Sep 13 17:01:57 2022
#      by: pyside2-uic  running on PySide2 5.12.5
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_main_widget(object):
    def setupUi(self, main_widget):
        main_widget.setObjectName("main_widget")
        main_widget.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(main_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.flag_commend_layout = QtWidgets.QFormLayout()
        self.flag_commend_layout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.flag_commend_layout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.flag_commend_layout.setContentsMargins(2, 2, 2, 2)
        self.flag_commend_layout.setHorizontalSpacing(8)
        self.flag_commend_layout.setVerticalSpacing(4)
        self.flag_commend_layout.setObjectName("flag_commend_layout")
        self.targetObj_label = QtWidgets.QLabel(main_widget)
        self.targetObj_label.setMinimumSize(QtCore.QSize(140, 0))
        self.targetObj_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.targetObj_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.targetObj_label.setObjectName("targetObj_label")
        self.flag_commend_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.targetObj_label)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.targetGetObj_LE = QtWidgets.QLineEdit(main_widget)
        self.targetGetObj_LE.setObjectName("targetGetObj_LE")
        self.horizontalLayout_11.addWidget(self.targetGetObj_LE)
        self.targetGetObj_PB = QtWidgets.QPushButton(main_widget)
        self.targetGetObj_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.targetGetObj_PB.setObjectName("targetGetObj_PB")
        self.horizontalLayout_11.addWidget(self.targetGetObj_PB)
        self.flag_commend_layout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.replacedWithObj_label = QtWidgets.QLabel(main_widget)
        self.replacedWithObj_label.setMinimumSize(QtCore.QSize(140, 0))
        self.replacedWithObj_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.replacedWithObj_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.replacedWithObj_label.setObjectName("replacedWithObj_label")
        self.flag_commend_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.replacedWithObj_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.replaceGetObj_LE = QtWidgets.QLineEdit(main_widget)
        self.replaceGetObj_LE.setObjectName("replaceGetObj_LE")
        self.horizontalLayout.addWidget(self.replaceGetObj_LE)
        self.replaceGetObj_PB = QtWidgets.QPushButton(main_widget)
        self.replaceGetObj_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.replaceGetObj_PB.setObjectName("replaceGetObj_PB")
        self.horizontalLayout.addWidget(self.replaceGetObj_PB)
        self.flag_commend_layout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.other_label = QtWidgets.QLabel(main_widget)
        self.other_label.setMinimumSize(QtCore.QSize(140, 0))
        self.other_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.other_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.other_label.setObjectName("other_label")
        self.flag_commend_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.other_label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dupDefaultRB = QtWidgets.QRadioButton(main_widget)
        self.dupDefaultRB.setChecked(True)
        self.dupDefaultRB.setObjectName("dupDefaultRB")
        self.horizontalLayout_3.addWidget(self.dupDefaultRB)
        self.dupInputGraph_RB = QtWidgets.QRadioButton(main_widget)
        self.dupInputGraph_RB.setObjectName("dupInputGraph_RB")
        self.horizontalLayout_3.addWidget(self.dupInputGraph_RB)
        self.dupInputConnections_RB = QtWidgets.QRadioButton(main_widget)
        self.dupInputConnections_RB.setObjectName("dupInputConnections_RB")
        self.horizontalLayout_3.addWidget(self.dupInputConnections_RB)
        self.duplicate_PB = QtWidgets.QPushButton(main_widget)
        self.duplicate_PB.setMinimumSize(QtCore.QSize(120, 0))
        self.duplicate_PB.setObjectName("duplicate_PB")
        self.horizontalLayout_3.addWidget(self.duplicate_PB)
        self.flag_commend_layout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.flag_commend_layout)
        self.line = QtWidgets.QFrame(main_widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.flag_commend_layout_2 = QtWidgets.QFormLayout()
        self.flag_commend_layout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.flag_commend_layout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.flag_commend_layout_2.setContentsMargins(2, 2, 2, 2)
        self.flag_commend_layout_2.setHorizontalSpacing(8)
        self.flag_commend_layout_2.setVerticalSpacing(4)
        self.flag_commend_layout_2.setObjectName("flag_commend_layout_2")
        self.targetVdb_label = QtWidgets.QLabel(main_widget)
        self.targetVdb_label.setMinimumSize(QtCore.QSize(140, 0))
        self.targetVdb_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.targetVdb_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.targetVdb_label.setObjectName("targetVdb_label")
        self.flag_commend_layout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.targetVdb_label)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(2)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.tanslateMin_label = QtWidgets.QLabel(main_widget)
        self.tanslateMin_label.setObjectName("tanslateMin_label")
        self.horizontalLayout_14.addWidget(self.tanslateMin_label)
        self.translateMin_LE = QtWidgets.QLineEdit(main_widget)
        self.translateMin_LE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.translateMin_LE.setMaxLength(32770)
        self.translateMin_LE.setObjectName("translateMin_LE")
        self.horizontalLayout_14.addWidget(self.translateMin_LE)
        self.tanslateMax_label = QtWidgets.QLabel(main_widget)
        self.tanslateMax_label.setObjectName("tanslateMax_label")
        self.horizontalLayout_14.addWidget(self.tanslateMax_label)
        self.translateMax_LE = QtWidgets.QLineEdit(main_widget)
        self.translateMax_LE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.translateMax_LE.setObjectName("translateMax_LE")
        self.horizontalLayout_14.addWidget(self.translateMax_LE)
        self.TX_CB = QtWidgets.QCheckBox(main_widget)
        self.TX_CB.setObjectName("TX_CB")
        self.horizontalLayout_14.addWidget(self.TX_CB)
        self.TY_CB = QtWidgets.QCheckBox(main_widget)
        self.TY_CB.setObjectName("TY_CB")
        self.horizontalLayout_14.addWidget(self.TY_CB)
        self.TZ_CB = QtWidgets.QCheckBox(main_widget)
        self.TZ_CB.setObjectName("TZ_CB")
        self.horizontalLayout_14.addWidget(self.TZ_CB)
        self.setTranslate_PB = QtWidgets.QPushButton(main_widget)
        self.setTranslate_PB.setObjectName("setTranslate_PB")
        self.horizontalLayout_14.addWidget(self.setTranslate_PB)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        self.flag_commend_layout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_14)
        self.vdbFile_label = QtWidgets.QLabel(main_widget)
        self.vdbFile_label.setMinimumSize(QtCore.QSize(140, 0))
        self.vdbFile_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.vdbFile_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vdbFile_label.setObjectName("vdbFile_label")
        self.flag_commend_layout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.vdbFile_label)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(2)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.rotateMin_label = QtWidgets.QLabel(main_widget)
        self.rotateMin_label.setObjectName("rotateMin_label")
        self.horizontalLayout_13.addWidget(self.rotateMin_label)
        self.rotateMin_LE = QtWidgets.QLineEdit(main_widget)
        self.rotateMin_LE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.rotateMin_LE.setObjectName("rotateMin_LE")
        self.horizontalLayout_13.addWidget(self.rotateMin_LE)
        self.rotateMax_label = QtWidgets.QLabel(main_widget)
        self.rotateMax_label.setObjectName("rotateMax_label")
        self.horizontalLayout_13.addWidget(self.rotateMax_label)
        self.rotateMax_LE = QtWidgets.QLineEdit(main_widget)
        self.rotateMax_LE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.rotateMax_LE.setObjectName("rotateMax_LE")
        self.horizontalLayout_13.addWidget(self.rotateMax_LE)
        self.RX_CB = QtWidgets.QCheckBox(main_widget)
        self.RX_CB.setObjectName("RX_CB")
        self.horizontalLayout_13.addWidget(self.RX_CB)
        self.RY_CB = QtWidgets.QCheckBox(main_widget)
        self.RY_CB.setObjectName("RY_CB")
        self.horizontalLayout_13.addWidget(self.RY_CB)
        self.RZ_CB = QtWidgets.QCheckBox(main_widget)
        self.RZ_CB.setObjectName("RZ_CB")
        self.horizontalLayout_13.addWidget(self.RZ_CB)
        self.setRotate_PB = QtWidgets.QPushButton(main_widget)
        self.setRotate_PB.setObjectName("setRotate_PB")
        self.horizontalLayout_13.addWidget(self.setRotate_PB)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.flag_commend_layout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_13)
        self.vdbSg_label = QtWidgets.QLabel(main_widget)
        self.vdbSg_label.setMinimumSize(QtCore.QSize(140, 0))
        self.vdbSg_label.setMaximumSize(QtCore.QSize(140, 16777215))
        self.vdbSg_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vdbSg_label.setObjectName("vdbSg_label")
        self.flag_commend_layout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.vdbSg_label)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.s_min_label = QtWidgets.QLabel(main_widget)
        self.s_min_label.setObjectName("s_min_label")
        self.horizontalLayout_5.addWidget(self.s_min_label)
        self.scaleMin_LE = QtWidgets.QLineEdit(main_widget)
        self.scaleMin_LE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.scaleMin_LE.setText("")
        self.scaleMin_LE.setObjectName("scaleMin_LE")
        self.horizontalLayout_5.addWidget(self.scaleMin_LE)
        self.s_max_label = QtWidgets.QLabel(main_widget)
        self.s_max_label.setObjectName("s_max_label")
        self.horizontalLayout_5.addWidget(self.s_max_label)
        self.scaleMax_LE = QtWidgets.QLineEdit(main_widget)
        self.scaleMax_LE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.scaleMax_LE.setObjectName("scaleMax_LE")
        self.horizontalLayout_5.addWidget(self.scaleMax_LE)
        self.SX_CB = QtWidgets.QCheckBox(main_widget)
        self.SX_CB.setEnabled(False)
        self.SX_CB.setChecked(True)
        self.SX_CB.setTristate(False)
        self.SX_CB.setObjectName("SX_CB")
        self.horizontalLayout_5.addWidget(self.SX_CB)
        self.SY_CB = QtWidgets.QCheckBox(main_widget)
        self.SY_CB.setEnabled(False)
        self.SY_CB.setChecked(True)
        self.SY_CB.setObjectName("SY_CB")
        self.horizontalLayout_5.addWidget(self.SY_CB)
        self.SZ_CB = QtWidgets.QCheckBox(main_widget)
        self.SZ_CB.setEnabled(False)
        self.SZ_CB.setChecked(True)
        self.SZ_CB.setObjectName("SZ_CB")
        self.horizontalLayout_5.addWidget(self.SZ_CB)
        self.scaleFreeze_CB = QtWidgets.QCheckBox(main_widget)
        self.scaleFreeze_CB.setChecked(True)
        self.scaleFreeze_CB.setObjectName("scaleFreeze_CB")
        self.horizontalLayout_5.addWidget(self.scaleFreeze_CB)
        self.setScale_PB = QtWidgets.QPushButton(main_widget)
        self.setScale_PB.setObjectName("setScale_PB")
        self.horizontalLayout_5.addWidget(self.setScale_PB)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.flag_commend_layout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.setAllRandom_PB = QtWidgets.QPushButton(main_widget)
        self.setAllRandom_PB.setObjectName("setAllRandom_PB")
        self.horizontalLayout_4.addWidget(self.setAllRandom_PB)
        self.flag_commend_layout_2.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.flag_commend_layout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)

        self.retranslateUi(main_widget)
        QtCore.QMetaObject.connectSlotsByName(main_widget)

    def retranslateUi(self, main_widget):
        main_widget.setWindowTitle(QtWidgets.QApplication.translate("main_widget", "Form", None, -1))
        self.targetObj_label.setText(QtWidgets.QApplication.translate("main_widget", "Target Object", None, -1))
        self.targetGetObj_PB.setText(QtWidgets.QApplication.translate("main_widget", "get obj", None, -1))
        self.replacedWithObj_label.setText(QtWidgets.QApplication.translate("main_widget", "Replaced With Object", None, -1))
        self.replaceGetObj_PB.setText(QtWidgets.QApplication.translate("main_widget", "get obj", None, -1))
        self.other_label.setText(QtWidgets.QApplication.translate("main_widget", "Duplicate Object", None, -1))
        self.dupDefaultRB.setText(QtWidgets.QApplication.translate("main_widget", "default", None, -1))
        self.dupInputGraph_RB.setText(QtWidgets.QApplication.translate("main_widget", "duplicate input graph", None, -1))
        self.dupInputConnections_RB.setText(QtWidgets.QApplication.translate("main_widget", "duplicate input connections", None, -1))
        self.duplicate_PB.setText(QtWidgets.QApplication.translate("main_widget", "duplicate", None, -1))
        self.targetVdb_label.setText(QtWidgets.QApplication.translate("main_widget", "Translate", None, -1))
        self.tanslateMin_label.setText(QtWidgets.QApplication.translate("main_widget", "min", None, -1))
        self.tanslateMax_label.setText(QtWidgets.QApplication.translate("main_widget", "max", None, -1))
        self.TX_CB.setText(QtWidgets.QApplication.translate("main_widget", "X", None, -1))
        self.TY_CB.setText(QtWidgets.QApplication.translate("main_widget", "Y", None, -1))
        self.TZ_CB.setText(QtWidgets.QApplication.translate("main_widget", "Z", None, -1))
        self.setTranslate_PB.setText(QtWidgets.QApplication.translate("main_widget", "Set random", None, -1))
        self.vdbFile_label.setText(QtWidgets.QApplication.translate("main_widget", "rotate", None, -1))
        self.rotateMin_label.setText(QtWidgets.QApplication.translate("main_widget", "min", None, -1))
        self.rotateMax_label.setText(QtWidgets.QApplication.translate("main_widget", "max", None, -1))
        self.RX_CB.setText(QtWidgets.QApplication.translate("main_widget", "X", None, -1))
        self.RY_CB.setText(QtWidgets.QApplication.translate("main_widget", "Y", None, -1))
        self.RZ_CB.setText(QtWidgets.QApplication.translate("main_widget", "Z", None, -1))
        self.setRotate_PB.setText(QtWidgets.QApplication.translate("main_widget", "Set random", None, -1))
        self.vdbSg_label.setText(QtWidgets.QApplication.translate("main_widget", "Scale", None, -1))
        self.s_min_label.setText(QtWidgets.QApplication.translate("main_widget", "min", None, -1))
        self.s_max_label.setText(QtWidgets.QApplication.translate("main_widget", "max", None, -1))
        self.SX_CB.setText(QtWidgets.QApplication.translate("main_widget", "X", None, -1))
        self.SY_CB.setText(QtWidgets.QApplication.translate("main_widget", "Y", None, -1))
        self.SZ_CB.setText(QtWidgets.QApplication.translate("main_widget", "Z", None, -1))
        self.scaleFreeze_CB.setText(QtWidgets.QApplication.translate("main_widget", "Freeze", None, -1))
        self.setScale_PB.setText(QtWidgets.QApplication.translate("main_widget", "Set random", None, -1))
        self.setAllRandom_PB.setText(QtWidgets.QApplication.translate("main_widget", "Set all random", None, -1))

