# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/chihjung/Documents/maya/2017/scripts/ui/redShiftTools_objSet_matte.ui'
#
# Created: Tue Jan 23 17:42:32 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_main_widget(object):
    def setupUi(self, main_widget):
        main_widget.setObjectName("main_widget")
        main_widget.resize(500, 497)
        self.verticalLayout = QtWidgets.QVBoxLayout(main_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.matte_label = QtWidgets.QLabel(main_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.matte_label.setFont(font)
        self.matte_label.setAlignment(QtCore.Qt.AlignCenter)
        self.matte_label.setObjectName("matte_label")
        self.verticalLayout.addWidget(self.matte_label)
        self.matteBig_layout = QtWidgets.QFormLayout()
        self.matteBig_layout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.matteBig_layout.setLabelAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.matteBig_layout.setFormAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.matteBig_layout.setSpacing(4)
        self.matteBig_layout.setObjectName("matteBig_layout")
        self.matteEnable_CB = QtWidgets.QCheckBox(main_widget)
        self.matteEnable_CB.setObjectName("matteEnable_CB")
        self.matteBig_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.matteEnable_CB)
        self.matteShowBackground_CB = QtWidgets.QCheckBox(main_widget)
        self.matteShowBackground_CB.setObjectName("matteShowBackground_CB")
        self.matteBig_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.matteShowBackground_CB)
        self.matteApplyToSecondaryRays_CB = QtWidgets.QCheckBox(main_widget)
        self.matteApplyToSecondaryRays_CB.setObjectName("matteApplyToSecondaryRays_CB")
        self.matteBig_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.matteApplyToSecondaryRays_CB)
        self.matteAlpha_label = QtWidgets.QLabel(main_widget)
        self.matteAlpha_label.setMinimumSize(QtCore.QSize(150, 0))
        self.matteAlpha_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matteAlpha_label.setObjectName("matteAlpha_label")
        self.matteBig_layout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.matteAlpha_label)
        self.matteAlpha_layout = QtWidgets.QHBoxLayout()
        self.matteAlpha_layout.setObjectName("matteAlpha_layout")
        self.matteAlpha_LE = QtWidgets.QLineEdit(main_widget)
        self.matteAlpha_LE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.matteAlpha_LE.setObjectName("matteAlpha_LE")
        self.matteAlpha_layout.addWidget(self.matteAlpha_LE)
        self.matteAlpha_slider = QtWidgets.QSlider(main_widget)
        self.matteAlpha_slider.setMaximum(100)
        self.matteAlpha_slider.setPageStep(8)
        self.matteAlpha_slider.setOrientation(QtCore.Qt.Horizontal)
        self.matteAlpha_slider.setObjectName("matteAlpha_slider")
        self.matteAlpha_layout.addWidget(self.matteAlpha_slider)
        self.matteBig_layout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.matteAlpha_layout)
        self.matteReflection_label = QtWidgets.QLabel(main_widget)
        self.matteReflection_label.setMinimumSize(QtCore.QSize(150, 0))
        self.matteReflection_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matteReflection_label.setObjectName("matteReflection_label")
        self.matteBig_layout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.matteReflection_label)
        self.matteReflectionScale_layout = QtWidgets.QHBoxLayout()
        self.matteReflectionScale_layout.setObjectName("matteReflectionScale_layout")
        self.matteReflectionScale_LE = QtWidgets.QLineEdit(main_widget)
        self.matteReflectionScale_LE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.matteReflectionScale_LE.setObjectName("matteReflectionScale_LE")
        self.matteReflectionScale_layout.addWidget(self.matteReflectionScale_LE)
        self.matteReflectionScale_slider = QtWidgets.QSlider(main_widget)
        self.matteReflectionScale_slider.setMaximum(100)
        self.matteReflectionScale_slider.setOrientation(QtCore.Qt.Horizontal)
        self.matteReflectionScale_slider.setObjectName("matteReflectionScale_slider")
        self.matteReflectionScale_layout.addWidget(self.matteReflectionScale_slider)
        self.matteBig_layout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.matteReflectionScale_layout)
        self.matteRefractionScale_layout = QtWidgets.QHBoxLayout()
        self.matteRefractionScale_layout.setObjectName("matteRefractionScale_layout")
        self.matteRefractionScale_LE = QtWidgets.QLineEdit(main_widget)
        self.matteRefractionScale_LE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.matteRefractionScale_LE.setObjectName("matteRefractionScale_LE")
        self.matteRefractionScale_layout.addWidget(self.matteRefractionScale_LE)
        self.matteRefractionScale_slider = QtWidgets.QSlider(main_widget)
        self.matteRefractionScale_slider.setMaximum(100)
        self.matteRefractionScale_slider.setOrientation(QtCore.Qt.Horizontal)
        self.matteRefractionScale_slider.setObjectName("matteRefractionScale_slider")
        self.matteRefractionScale_layout.addWidget(self.matteRefractionScale_slider)
        self.matteBig_layout.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.matteRefractionScale_layout)
        self.matteAffectedByMatteLights_CB = QtWidgets.QCheckBox(main_widget)
        self.matteAffectedByMatteLights_CB.setObjectName("matteAffectedByMatteLights_CB")
        self.matteBig_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.matteAffectedByMatteLights_CB)
        self.matteNoSelfShadow_CB = QtWidgets.QCheckBox(main_widget)
        self.matteNoSelfShadow_CB.setObjectName("matteNoSelfShadow_CB")
        self.matteBig_layout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.matteNoSelfShadow_CB)
        self.matteRefractionScale_label = QtWidgets.QLabel(main_widget)
        self.matteRefractionScale_label.setMinimumSize(QtCore.QSize(150, 0))
        self.matteRefractionScale_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matteRefractionScale_label.setObjectName("matteRefractionScale_label")
        self.matteBig_layout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.matteRefractionScale_label)
        self.matteDiffuseScale_label = QtWidgets.QLabel(main_widget)
        self.matteDiffuseScale_label.setMinimumSize(QtCore.QSize(150, 0))
        self.matteDiffuseScale_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matteDiffuseScale_label.setObjectName("matteDiffuseScale_label")
        self.matteBig_layout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.matteDiffuseScale_label)
        self.matteDiffuseScale_layout = QtWidgets.QHBoxLayout()
        self.matteDiffuseScale_layout.setObjectName("matteDiffuseScale_layout")
        self.matteDiffuseScale_LE = QtWidgets.QLineEdit(main_widget)
        self.matteDiffuseScale_LE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.matteDiffuseScale_LE.setObjectName("matteDiffuseScale_LE")
        self.matteDiffuseScale_layout.addWidget(self.matteDiffuseScale_LE)
        self.matteDiffuseScale_slider = QtWidgets.QSlider(main_widget)
        self.matteDiffuseScale_slider.setMaximum(100)
        self.matteDiffuseScale_slider.setOrientation(QtCore.Qt.Horizontal)
        self.matteDiffuseScale_slider.setObjectName("matteDiffuseScale_slider")
        self.matteDiffuseScale_layout.addWidget(self.matteDiffuseScale_slider)
        self.matteBig_layout.setLayout(8, QtWidgets.QFormLayout.FieldRole, self.matteDiffuseScale_layout)
        self.verticalLayout.addLayout(self.matteBig_layout)
        self.frame = QtWidgets.QFrame(main_widget)
        self.frame.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.shadow_label = QtWidgets.QLabel(main_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.shadow_label.setFont(font)
        self.shadow_label.setAlignment(QtCore.Qt.AlignCenter)
        self.shadow_label.setObjectName("shadow_label")
        self.verticalLayout.addWidget(self.shadow_label)
        self.shadowBig_layout = QtWidgets.QFormLayout()
        self.shadowBig_layout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.shadowBig_layout.setLabelAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.shadowBig_layout.setFormAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.shadowBig_layout.setSpacing(4)
        self.shadowBig_layout.setObjectName("shadowBig_layout")
        self.shadowEnable_CB = QtWidgets.QCheckBox(main_widget)
        self.shadowEnable_CB.setObjectName("shadowEnable_CB")
        self.shadowBig_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.shadowEnable_CB)
        self.shadowAffectAlpha_CB = QtWidgets.QCheckBox(main_widget)
        self.shadowAffectAlpha_CB.setObjectName("shadowAffectAlpha_CB")
        self.shadowBig_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.shadowAffectAlpha_CB)
        self.shadowColor_label = QtWidgets.QLabel(main_widget)
        self.shadowColor_label.setMinimumSize(QtCore.QSize(150, 0))
        self.shadowColor_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.shadowColor_label.setObjectName("shadowColor_label")
        self.shadowBig_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.shadowColor_label)
        self.shadowColor_layout = QtWidgets.QHBoxLayout()
        self.shadowColor_layout.setObjectName("shadowColor_layout")
        self.shadowColorSet_PB = QtWidgets.QPushButton(main_widget)
        self.shadowColorSet_PB.setMinimumSize(QtCore.QSize(80, 20))
        self.shadowColorSet_PB.setMaximumSize(QtCore.QSize(80, 20))
        self.shadowColorSet_PB.setCheckable(False)
        self.shadowColorSet_PB.setAutoDefault(False)
        self.shadowColorSet_PB.setDefault(False)
        self.shadowColorSet_PB.setFlat(False)
        self.shadowColorSet_PB.setObjectName("shadowColorSet_PB")
        self.shadowColor_layout.addWidget(self.shadowColorSet_PB)
        self.shadowColor_slider = QtWidgets.QSlider(main_widget)
        self.shadowColor_slider.setMaximum(100)
        self.shadowColor_slider.setSingleStep(1)
        self.shadowColor_slider.setOrientation(QtCore.Qt.Horizontal)
        self.shadowColor_slider.setObjectName("shadowColor_slider")
        self.shadowColor_layout.addWidget(self.shadowColor_slider)
        self.shadowBig_layout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.shadowColor_layout)
        self.shadowTransparency_label = QtWidgets.QLabel(main_widget)
        self.shadowTransparency_label.setMinimumSize(QtCore.QSize(150, 0))
        self.shadowTransparency_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.shadowTransparency_label.setObjectName("shadowTransparency_label")
        self.shadowBig_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.shadowTransparency_label)
        self.shadowTransparency_layout = QtWidgets.QHBoxLayout()
        self.shadowTransparency_layout.setObjectName("shadowTransparency_layout")
        self.shadowTransparency_LE = QtWidgets.QLineEdit(main_widget)
        self.shadowTransparency_LE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.shadowTransparency_LE.setObjectName("shadowTransparency_LE")
        self.shadowTransparency_layout.addWidget(self.shadowTransparency_LE)
        self.shadowTransparency_slider = QtWidgets.QSlider(main_widget)
        self.shadowTransparency_slider.setMaximum(100)
        self.shadowTransparency_slider.setOrientation(QtCore.Qt.Horizontal)
        self.shadowTransparency_slider.setObjectName("shadowTransparency_slider")
        self.shadowTransparency_layout.addWidget(self.shadowTransparency_slider)
        self.shadowBig_layout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.shadowTransparency_layout)
        self.verticalLayout.addLayout(self.shadowBig_layout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(main_widget)
        QtCore.QMetaObject.connectSlotsByName(main_widget)

    def retranslateUi(self, main_widget):
        main_widget.setWindowTitle(QtWidgets.QApplication.translate("main_widget", "Form", None, -1))
        self.matte_label.setText(QtWidgets.QApplication.translate("main_widget", "Matte", None, -1))
        self.matteEnable_CB.setText(QtWidgets.QApplication.translate("main_widget", "Enable", None, -1))
        self.matteShowBackground_CB.setText(QtWidgets.QApplication.translate("main_widget", "Show Background", None, -1))
        self.matteApplyToSecondaryRays_CB.setText(QtWidgets.QApplication.translate("main_widget", "Apply To Secondary Rays", None, -1))
        self.matteAlpha_label.setText(QtWidgets.QApplication.translate("main_widget", "Alpha", None, -1))
        self.matteReflection_label.setText(QtWidgets.QApplication.translate("main_widget", "Reflection Scale", None, -1))
        self.matteAffectedByMatteLights_CB.setText(QtWidgets.QApplication.translate("main_widget", "Affected By Matte Lights", None, -1))
        self.matteNoSelfShadow_CB.setText(QtWidgets.QApplication.translate("main_widget", "No Self Shadow", None, -1))
        self.matteRefractionScale_label.setText(QtWidgets.QApplication.translate("main_widget", "Refraction Scale", None, -1))
        self.matteDiffuseScale_label.setText(QtWidgets.QApplication.translate("main_widget", "Diffuse Scale", None, -1))
        self.shadow_label.setText(QtWidgets.QApplication.translate("main_widget", "Shadow", None, -1))
        self.shadowEnable_CB.setText(QtWidgets.QApplication.translate("main_widget", "Enable", None, -1))
        self.shadowAffectAlpha_CB.setText(QtWidgets.QApplication.translate("main_widget", "Affects Alpha", None, -1))
        self.shadowColor_label.setText(QtWidgets.QApplication.translate("main_widget", "color", None, -1))
        self.shadowColorSet_PB.setText(QtWidgets.QApplication.translate("main_widget", "RGB", None, -1))
        self.shadowTransparency_label.setText(QtWidgets.QApplication.translate("main_widget", "Transparency", None, -1))

