# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/chihjung/Documents/maya/2017/scripts/ui/shadingToolsMeshLink.ui'
#
# Created: Thu Nov 30 09:25:29 2017
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_main_widget(object):
    def setupUi(self, main_widget):
        main_widget.setObjectName("main_widget")
        main_widget.resize(800, 592)
        self.verticalLayout = QtWidgets.QVBoxLayout(main_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.analyzeShadingLink_PB = QtWidgets.QPushButton(main_widget)
        self.analyzeShadingLink_PB.setObjectName("analyzeShadingLink_PB")
        self.verticalLayout.addWidget(self.analyzeShadingLink_PB)
        self.info_label = QtWidgets.QLabel(main_widget)
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setObjectName("info_label")
        self.verticalLayout.addWidget(self.info_label)
        self.shading_link_treeWidget = QtWidgets.QTreeWidget(main_widget)
        self.shading_link_treeWidget.setObjectName("shading_link_treeWidget")
        self.verticalLayout.addWidget(self.shading_link_treeWidget)
        self.tree_PB_layout = QtWidgets.QHBoxLayout()
        self.tree_PB_layout.setSpacing(2)
        self.tree_PB_layout.setObjectName("tree_PB_layout")
        self.expanded_all_PB = QtWidgets.QPushButton(main_widget)
        self.expanded_all_PB.setObjectName("expanded_all_PB")
        self.tree_PB_layout.addWidget(self.expanded_all_PB)
        self.expanded_off_PB = QtWidgets.QPushButton(main_widget)
        self.expanded_off_PB.setObjectName("expanded_off_PB")
        self.tree_PB_layout.addWidget(self.expanded_off_PB)
        self.select_all_PB = QtWidgets.QPushButton(main_widget)
        self.select_all_PB.setObjectName("select_all_PB")
        self.tree_PB_layout.addWidget(self.select_all_PB)
        self.select_clean_PB = QtWidgets.QPushButton(main_widget)
        self.select_clean_PB.setObjectName("select_clean_PB")
        self.tree_PB_layout.addWidget(self.select_clean_PB)
        self.verticalLayout.addLayout(self.tree_PB_layout)
        self.infor_formLayout = QtWidgets.QFormLayout()
        self.infor_formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.infor_formLayout.setSpacing(2)
        self.infor_formLayout.setObjectName("infor_formLayout")
        self.objName_label = QtWidgets.QLabel(main_widget)
        self.objName_label.setObjectName("objName_label")
        self.infor_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.objName_label)
        self.objName_LE = QtWidgets.QLineEdit(main_widget)
        self.objName_LE.setMaximumSize(QtCore.QSize(200, 16777215))
        self.objName_LE.setObjectName("objName_LE")
        self.infor_formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.objName_LE)
        self.cachePath_label = QtWidgets.QLabel(main_widget)
        self.cachePath_label.setObjectName("cachePath_label")
        self.infor_formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.cachePath_label)
        self.cachePath_layout = QtWidgets.QHBoxLayout()
        self.cachePath_layout.setSpacing(2)
        self.cachePath_layout.setContentsMargins(0, 0, 0, 0)
        self.cachePath_layout.setObjectName("cachePath_layout")
        self.cachePath_LE = QtWidgets.QLineEdit(main_widget)
        self.cachePath_LE.setObjectName("cachePath_LE")
        self.cachePath_layout.addWidget(self.cachePath_LE)
        self.cachePath_bro_PB = QtWidgets.QPushButton(main_widget)
        self.cachePath_bro_PB.setMaximumSize(QtCore.QSize(20, 16777215))
        self.cachePath_bro_PB.setObjectName("cachePath_bro_PB")
        self.cachePath_layout.addWidget(self.cachePath_bro_PB)
        self.cachePath_open_PB = QtWidgets.QPushButton(main_widget)
        self.cachePath_open_PB.setObjectName("cachePath_open_PB")
        self.cachePath_layout.addWidget(self.cachePath_open_PB)
        self.infor_formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.cachePath_layout)
        self.verticalLayout.addLayout(self.infor_formLayout)
        self.bottom_PB_layout = QtWidgets.QGridLayout()
        self.bottom_PB_layout.setContentsMargins(0, 0, 0, 0)
        self.bottom_PB_layout.setSpacing(2)
        self.bottom_PB_layout.setObjectName("bottom_PB_layout")
        self.convert_redShift_PB = QtWidgets.QPushButton(main_widget)
        self.convert_redShift_PB.setObjectName("convert_redShift_PB")
        self.bottom_PB_layout.addWidget(self.convert_redShift_PB, 1, 3, 1, 1)
        self.convert_prman_PB = QtWidgets.QPushButton(main_widget)
        self.convert_prman_PB.setCheckable(False)
        self.convert_prman_PB.setObjectName("convert_prman_PB")
        self.bottom_PB_layout.addWidget(self.convert_prman_PB, 1, 1, 1, 1)
        self.convert_stingray_PB = QtWidgets.QPushButton(main_widget)
        self.convert_stingray_PB.setObjectName("convert_stingray_PB")
        self.bottom_PB_layout.addWidget(self.convert_stingray_PB, 1, 2, 1, 1)
        self.export_prman_PB = QtWidgets.QPushButton(main_widget)
        self.export_prman_PB.setObjectName("export_prman_PB")
        self.bottom_PB_layout.addWidget(self.export_prman_PB, 0, 1, 1, 1)
        self.export_redShift_PB = QtWidgets.QPushButton(main_widget)
        self.export_redShift_PB.setObjectName("export_redShift_PB")
        self.bottom_PB_layout.addWidget(self.export_redShift_PB, 0, 3, 1, 1)
        self.export_stingray_PB = QtWidgets.QPushButton(main_widget)
        self.export_stingray_PB.setObjectName("export_stingray_PB")
        self.bottom_PB_layout.addWidget(self.export_stingray_PB, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.bottom_PB_layout)

        self.retranslateUi(main_widget)
        QtCore.QMetaObject.connectSlotsByName(main_widget)

    def retranslateUi(self, main_widget):
        main_widget.setWindowTitle(QtWidgets.QApplication.translate("main_widget", "Form", None, -1))
        self.analyzeShadingLink_PB.setText(QtWidgets.QApplication.translate("main_widget", "analyze shading link", None, -1))
        self.info_label.setText(QtWidgets.QApplication.translate("main_widget", "please select group or mesh , then analyze it.", None, -1))
        self.shading_link_treeWidget.headerItem().setText(0, QtWidgets.QApplication.translate("main_widget", "mesh name", None, -1))
        self.shading_link_treeWidget.headerItem().setText(1, QtWidgets.QApplication.translate("main_widget", "render engine", None, -1))
        self.expanded_all_PB.setText(QtWidgets.QApplication.translate("main_widget", "expanded all", None, -1))
        self.expanded_off_PB.setText(QtWidgets.QApplication.translate("main_widget", "expanded off", None, -1))
        self.select_all_PB.setText(QtWidgets.QApplication.translate("main_widget", "select all", None, -1))
        self.select_clean_PB.setText(QtWidgets.QApplication.translate("main_widget", "select clean", None, -1))
        self.objName_label.setText(QtWidgets.QApplication.translate("main_widget", "object name : ", None, -1))
        self.cachePath_label.setText(QtWidgets.QApplication.translate("main_widget", "data cache path : ", None, -1))
        self.cachePath_bro_PB.setText(QtWidgets.QApplication.translate("main_widget", "...", None, -1))
        self.cachePath_open_PB.setText(QtWidgets.QApplication.translate("main_widget", "open", None, -1))
        self.convert_redShift_PB.setText(QtWidgets.QApplication.translate("main_widget", "convert to redShift", None, -1))
        self.convert_prman_PB.setText(QtWidgets.QApplication.translate("main_widget", "convert to renderman", None, -1))
        self.convert_stingray_PB.setText(QtWidgets.QApplication.translate("main_widget", "convert to stingray", None, -1))
        self.export_prman_PB.setText(QtWidgets.QApplication.translate("main_widget", "export renderman", None, -1))
        self.export_redShift_PB.setText(QtWidgets.QApplication.translate("main_widget", "export to redShift", None, -1))
        self.export_stingray_PB.setText(QtWidgets.QApplication.translate("main_widget", "export stingray", None, -1))

