# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/chihjung/Documents/maya/2023/scripts/ui/shadingToolsCreateNodes.ui',
# licensing of 'C:/Users/chihjung/Documents/maya/2023/scripts/ui/shadingToolsCreateNodes.ui' applies.
#
# Created: Thu Sep  8 12:14:43 2022
#      by: pyside2-uic  running on PySide2 5.12.5
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_main_widget(object):
    def setupUi(self, main_widget):
        main_widget.setObjectName("main_widget")
        main_widget.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(main_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setSpacing(4)
        self.formLayout_2.setObjectName("formLayout_2")
        self.texturePath_label = QtWidgets.QLabel(main_widget)
        self.texturePath_label.setMinimumSize(QtCore.QSize(120, 0))
        self.texturePath_label.setMaximumSize(QtCore.QSize(120, 16777215))
        self.texturePath_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.texturePath_label.setObjectName("texturePath_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.texturePath_label)
        self.texturePath_layout = QtWidgets.QHBoxLayout()
        self.texturePath_layout.setSpacing(4)
        self.texturePath_layout.setContentsMargins(0, 0, 0, 0)
        self.texturePath_layout.setObjectName("texturePath_layout")
        self.texturePath_LE = QtWidgets.QLineEdit(main_widget)
        self.texturePath_LE.setObjectName("texturePath_LE")
        self.texturePath_layout.addWidget(self.texturePath_LE)
        self.texturePathBro_PB = QtWidgets.QPushButton(main_widget)
        self.texturePathBro_PB.setMaximumSize(QtCore.QSize(20, 16777215))
        self.texturePathBro_PB.setObjectName("texturePathBro_PB")
        self.texturePath_layout.addWidget(self.texturePathBro_PB)
        self.texturePathOpen_PB = QtWidgets.QPushButton(main_widget)
        self.texturePathOpen_PB.setObjectName("texturePathOpen_PB")
        self.texturePath_layout.addWidget(self.texturePathOpen_PB)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.texturePath_layout)
        self.baseNameEdit_label = QtWidgets.QLabel(main_widget)
        self.baseNameEdit_label.setMinimumSize(QtCore.QSize(120, 0))
        self.baseNameEdit_label.setMaximumSize(QtCore.QSize(120, 16777215))
        self.baseNameEdit_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.baseNameEdit_label.setObjectName("baseNameEdit_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.baseNameEdit_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.exName_LE = QtWidgets.QLineEdit(main_widget)
        self.exName_LE.setReadOnly(True)
        self.exName_LE.setObjectName("exName_LE")
        self.horizontalLayout.addWidget(self.exName_LE)
        self.dot_CB = QtWidgets.QComboBox(main_widget)
        self.dot_CB.setObjectName("dot_CB")
        self.dot_CB.addItem("")
        self.dot_CB.addItem("")
        self.horizontalLayout.addWidget(self.dot_CB)
        self.udim_CB = QtWidgets.QCheckBox(main_widget)
        self.udim_CB.setObjectName("udim_CB")
        self.horizontalLayout.addWidget(self.udim_CB)
        self.ext_CB = QtWidgets.QComboBox(main_widget)
        self.ext_CB.setObjectName("ext_CB")
        self.ext_CB.addItem("")
        self.ext_CB.addItem("")
        self.ext_CB.addItem("")
        self.horizontalLayout.addWidget(self.ext_CB)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.analyzeTextureSets_PB = QtWidgets.QPushButton(main_widget)
        self.analyzeTextureSets_PB.setObjectName("analyzeTextureSets_PB")
        self.verticalLayout.addWidget(self.analyzeTextureSets_PB)
        self.scrollArea = QtWidgets.QScrollArea(main_widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 780, 441))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollAreaLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.scrollAreaLayout.setSpacing(4)
        self.scrollAreaLayout.setContentsMargins(2, 2, 2, 2)
        self.scrollAreaLayout.setObjectName("scrollAreaLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.bottom_label = QtWidgets.QLabel(main_widget)
        self.bottom_label.setObjectName("bottom_label")
        self.verticalLayout.addWidget(self.bottom_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prman_PB = QtWidgets.QPushButton(main_widget)
        self.prman_PB.setObjectName("prman_PB")
        self.horizontalLayout_2.addWidget(self.prman_PB)
        self.stingray_PB = QtWidgets.QPushButton(main_widget)
        self.stingray_PB.setObjectName("stingray_PB")
        self.horizontalLayout_2.addWidget(self.stingray_PB)
        self.redShift_PB = QtWidgets.QPushButton(main_widget)
        self.redShift_PB.setObjectName("redShift_PB")
        self.horizontalLayout_2.addWidget(self.redShift_PB)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(main_widget)
        QtCore.QMetaObject.connectSlotsByName(main_widget)

    def retranslateUi(self, main_widget):
        main_widget.setWindowTitle(QtWidgets.QApplication.translate("main_widget", "Form", None, -1))
        self.texturePath_label.setText(QtWidgets.QApplication.translate("main_widget", "SP textures path : ", None, -1))
        self.texturePathBro_PB.setText(QtWidgets.QApplication.translate("main_widget", "...", None, -1))
        self.texturePathOpen_PB.setText(QtWidgets.QApplication.translate("main_widget", "open", None, -1))
        self.baseNameEdit_label.setText(QtWidgets.QApplication.translate("main_widget", "Base name edit : ", None, -1))
        self.exName_LE.setText(QtWidgets.QApplication.translate("main_widget", "ex. dog_BaseColor.exr", None, -1))
        self.dot_CB.setItemText(0, QtWidgets.QApplication.translate("main_widget", ".", None, -1))
        self.dot_CB.setItemText(1, QtWidgets.QApplication.translate("main_widget", "_", None, -1))
        self.udim_CB.setText(QtWidgets.QApplication.translate("main_widget", "UDIM", None, -1))
        self.ext_CB.setItemText(0, QtWidgets.QApplication.translate("main_widget", "exr", None, -1))
        self.ext_CB.setItemText(1, QtWidgets.QApplication.translate("main_widget", "jpg", None, -1))
        self.ext_CB.setItemText(2, QtWidgets.QApplication.translate("main_widget", "png", None, -1))
        self.analyzeTextureSets_PB.setText(QtWidgets.QApplication.translate("main_widget", "analyze texture sets", None, -1))
        self.bottom_label.setText(QtWidgets.QApplication.translate("main_widget", "creating shader graphs", None, -1))
        self.prman_PB.setText(QtWidgets.QApplication.translate("main_widget", "renderman", None, -1))
        self.stingray_PB.setText(QtWidgets.QApplication.translate("main_widget", "stingray", None, -1))
        self.redShift_PB.setText(QtWidgets.QApplication.translate("main_widget", "redShift", None, -1))

